### ISSUE TITLE
Cannot read property 'readworkspace' of undefined.

### ISSUE THREAD

**Issue by abhinavbussa** [single-spa/single-spa-angular#462] opened 2022-12-06 07:48 UTC
When I try to add a single spa to the existing angular application which uses version 13.2.0, I face the above issue once I give the port number when the single spa is trying to configure.

**Comment by arturovt** [comment] 2022-12-29 19:50
Sorry, I have to close this issue because I’m not able to reproduce it locally and other users haven’t logged such issues before.

**Closed by arturovt** 2022-12-29 19:50 UTC
