### ISSUE TITLE
Run Angular Multiple Projects in One App Using Single-Spa

### ISSUE THREAD

**Issue by aniketavhad** [single-spa/single-spa-angular#152] opened 2020-03-25 07:34 UTC
I have a requirement to create, Two projects in same `angular.json` and Run both the projects at a time. But my observation says single-spa point to `"defaultProject": "My-App"` which is present in angular.json.

Without single-spa it is possible to run both projects using following command,
`ng s --project="My-App"` But the same way i can't able to run with single-spa. It gives me below error,

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.library should be one of these:
   string | [string] | object { root?, amd?, commonjs? }
   -> If set, export the bundle as library. `output.library` is the name.
   Details:
    * configuration.output.library should be a string.
    * configuration.output.library should be an array:
      [string]
    * configuration.output.library should be an object.
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.library should be one of these:
   string | [string] | object { root?, amd?, commonjs? }
   -> If set, export the bundle as library. `output.library` is the name.
   Details:
    * configuration.output.library should be a string.
    * configuration.output.library should be an array:
      [string]
    * configuration.output.library should be an object.
    at webpack (D:\manage\manage-master\frontend\node_modules\webpack\lib\webpack.js:24:9)
```

**Comment by joeldenning** [comment] 2020-03-25 20:02
This appears to be a duplicate of https://github.com/single-spa/single-spa-angular/issues/127. @Lykathia suggested a fix in that issue - I would be very open a pull request implementing the fix.

I'm closing this issue in favor of #127, so we can track it all in one place.

**Closed by joeldenning** 2020-03-25 20:02 UTC
