### ISSUE TITLE
single-spa Not found in version 4.1.0

### ISSUE THREAD

**Issue by jimmyhdolores** [single-spa/single-spa-angular#188] opened 2020-05-15 22:49 UTC
In version 3.0.1 single-spa is loaded, but now in this version 4.1.0 it no longer loads and therefore causes an error in the singleSpaPropsSubject class, note that you use the command ng add single-spa-angular

**Comment by joeldenning** [comment] 2020-05-16 00:33
`npm install --save single-spa`

single-spa-angular@3 and single-spa-angular@4 both have a peerDependency on single-spa. We made it a peer dependency because single-spa-angular@4 works with single-spa 3, 4, or 5 and we wanted to give people the option to use those versions if they are already on an older version.

The difference with single-spa-angular@4 is that single-spa is imported for its types in 4, whereas it isn't in single-spa-angular@3. There have been about ten people before you report this as a bug even though it's expected behavior. Which makes me think it was a bad choice to make it a peerDependency, even though that would make single-spa-angular@4 harder to use with newer older versions of single-spa.

Could you send in a pull request moving single-spa to be a dependency instead of a peerDependency?

**Comment by MarcoBomfim** [comment] 2020-05-18 14:54
I was just about to open the PR but noticed that single-spa is already a dependency (?): 
- [package.json:114](https://github.com/single-spa/single-spa-angular/blob/master/package.json#L114)

Or do you mean to throw it up as a devDependency?

**Comment by joeldenning** [comment] 2020-05-18 15:19
This project uses ng-packagr, which is a bit weird in that the package.json at the root of the project is not the one published to npm. See code below that shows that single-spa is a peerDependency:

https://github.com/single-spa/single-spa-angular/blob/ff2acca6fc66c12ad876d1dc883f45748822becf/src/package.json#L28

^ This is the package.json that needs to be updated.

**Comment by MarcoBomfim** [comment] 2020-05-18 18:58
I was overcomplicating things for some reason. Thanks!

**Comment by joeldenning** [comment] 2020-05-21 16:22
This was resolved in https://github.com/single-spa/single-spa-angular/pull/193. @filoxo added this as part of the angular schematics, which i think is an even better solution.

**Closed by joeldenning** 2020-05-21 16:22 UTC
