### ISSUE TITLE
Cannot enable prod mode when use Angular shared libraries

### ISSUE THREAD

**Issue by sxhieen** [single-spa/single-spa-angular#355] opened 2021-04-27 10:37 UTC
I have two Angular sub apps, both of them use Angular shared libraries, such as @angular/core, @angular/common, etc. But I can open only one of them for the first launch in prod environment. When I open another angular sub app, there is a error that "Cannot enable prod mode after platform setup.". After I remove "enableProdMode()" in main.single-spa.ts, everything is OK. Also, I don't remove "enableProdMode()" in main.single-spa.ts and don't use Angular shared libraries, everything is OK too.

**Comment by joeldenning** [comment] 2021-04-27 18:25
Transferring this to single-spa-angular

**Comment by arturovt** [comment] 2021-04-30 09:21
Well, this is not a bug and actually it's an expected behavior. You're sharing dependencies and calling the same `enableProdMode` function multiple times.

You can do these things:
1) call `enableProdMode` only once in the very root application that serves as a parent for all apps
2) wrap `enableProdMode()` into `try-catch` in child apps. That won't break anything since you'll just ignore the error

**Closed by arturovt** 2021-04-30 09:21 UTC
