### ISSUE TITLE
Add support for Angular 13

### ISSUE THREAD

**Issue by tymfear** [single-spa/single-spa-angular#395] opened 2021-11-04 12:51 UTC
Add support for the Angular 13 since it is out today

**Comment by SunilManthenaG01** [comment] 2021-11-09 15:27
Do we have any plan soon to update it to angular 13 ?

**Comment by joeldenning** [comment] 2021-11-09 21:48
@arturovt are you able to help with this? I do not have plans to work on this. The single-spa-angular project doesn't really have any maintainers and so if @arturovt doesn't have time to do so we'll wait for someone else from the community to help out with this.

**Comment by arturovt** [comment] 2021-11-09 22:45
Hey, what issues are you experiencing with Angular 13?

We don't use any functionality that was removed in Angular 13 (marked as a breaking change) within the library code. Angular 13 has just introduced the new package format (which is only related to how libraries are published and they're not run through the `ngcc` compiler).

I can't update this repo to Angular 13 since it uses Nx which is not compatible with Angular 13 yet.

**Comment by willsicko** [comment] 2021-11-09 23:52
Hi, I try in angular 13 and i have this problem
![image](https://user-images.githubusercontent.com/9969564/141024208-b33f8495-30e0-44b3-880a-2f91695d5af2.png)

**Comment by arturovt** [comment] 2021-11-10 00:17
Alright, this is because we’re using `VERSION` from `@angular/core`. Nx will release the next version soon so I’ll be able to check it and fix it.

**Comment by ALP011216** [comment] 2021-11-19 07:11
Hi,
a problem I ran into with Angular 13 was a webpack-dev-server config issue.
Now Angular uses a webpack-dev-server version` >= 4.0.0` so [contentBase](https://github.com/single-spa/single-spa-angular/blob/4c36be60195d98073fdc82567721a8e724e023d4/libs/single-spa-angular/webpack/index.ts#L38) isn't a supported config property anymore.
Using the `static` property instead of `contentBase` should solve the issue.

**Comment by jogelin** [comment] 2021-11-20 13:57
> Hi, a problem I ran into with Angular 13 was a webpack-dev-server config issue. Now Angular uses a webpack-dev-server version` >= 4.0.0` so [contentBase](https://github.com/single-spa/single-spa-angular/blob/4c36be60195d98073fdc82567721a8e724e023d4/libs/single-spa-angular/webpack/index.ts#L38) isn't a supported config property anymore. Using the `static` property instead of `contentBase` should solve the issue.

Same here, I patched the single-spa config for now:
```javascript
  const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);

  const singleSpaWebpackConfigPatched = {
    ...singleSpaWebpackConfig,
    devServer: {
      ...singleSpaWebpackConfig.devServer,
      static: singleSpaWebpackConfig.devServer.contentBase,
    },
  };
  delete singleSpaWebpackConfigPatched.devServer.contentBase;
```

**Comment by tscislo** [comment] 2021-12-06 16:41
@joeldenning @arturovt It would be great if we don't fall behind with Single SPA when it comes to Angular migrations. Currently to run Single SPA with newest Angular v 13 one needs to do this patch plus the one that I described in [#328.](https://github.com/single-spa/single-spa-angular/issues/328). There are still some people using Angular out there ;)

**Comment by arturovt** [comment] 2021-12-06 18:14
I made a PR 2 weeks ago (https://github.com/single-spa/single-spa-angular/pull/398), but it's awaiting review.

**Comment by tscislo** [comment] 2021-12-06 19:55
Great please approve @jogelin

**Comment by jogelin** [comment] 2021-12-15 08:10
I also see some errors in my console concerning HMR:

```
main.js:21586 WebSocket connection to 'wss://my-app-host/ws' failed: 
```

In fact, by default, the [client WebSocket of the Webpack dev-server](https://webpack.js.org/configuration/dev-server/#websocketurl) is using the current host but it should target the micro-frontend server instead.

So I added this in my webpack config:
```typescript
        devServer: {
      client: {
        webSocketURL: {
          hostname: config.devServer.host,
          port: config.devServer.port,
        },
      },
    },
```

I don't see the error anymore and I see now `[webpack-dev-server] App updated. Recompiling...` in my console when modifying my micro-frontend. But the module is not reloading, didn't investigate more yet.

@arturovt could you include that in your PR?

**Comment by nmccrack37** [comment] 2022-01-04 18:50
> > Hi, a problem I ran into with Angular 13 was a webpack-dev-server config issue. Now Angular uses a webpack-dev-server version` >= 4.0.0` so [contentBase](https://github.com/single-spa/single-spa-angular/blob/4c36be60195d98073fdc82567721a8e724e023d4/libs/single-spa-angular/webpack/index.ts#L38) isn't a supported config property anymore. Using the `static` property instead of `contentBase` should solve the issue.
> 
> Same here, I patched the single-spa config for now by [following webpack doc](https://webpack.js.org/configuration/dev-server/#directory):
> 
> ```js
>   const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);
> 
>   const singleSpaWebpackConfigPatched = {
>     ...singleSpaWebpackConfig,
>     devServer: {
>       ...singleSpaWebpackConfig.devServer,
>       static: {
>           directory: singleSpaWebpackConfigPatched.devServer.contentBase,
>         },
>       }
>     },
>   };
>   delete singleSpaWebpackConfigPatched.devServer.contentBase;
> ```

I'm attempting to implement this patch in my MFE, but I'm a little confused on how it all fits together - hoping you can help

Currently I have
`module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options)

  singleSpaWebpackConfig.entry.main = [...new Set(singleSpaWebpackConfig.entry.main)];

  return singleSpaWebpackConfig
}`

Where in there do I implement the Patched config?

**Comment by nmccrack37** [comment] 2022-01-04 18:52
> > Same here, I patched the single-spa config for now by [following webpack doc](https://webpack.js.org/configuration/dev-server/#directory):
> 
> ```js
>   const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);
> 
>   const singleSpaWebpackConfigPatched = {
>     ...singleSpaWebpackConfig,
>     devServer: {
>       ...singleSpaWebpackConfig.devServer,
>       static: {
>           directory: singleSpaWebpackConfigPatched.devServer.contentBase,
>         },
>       }
>     },
>   };
>   delete singleSpaWebpackConfigPatched.devServer.contentBase;
> ```
I'm attempting to implement this patch in my MFE but I'm a little confused on the syntax - hoping you can help

Currently my webpack is set up as follows
`module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options)

  singleSpaWebpackConfig.entry.main = [...new Set(singleSpaWebpackConfig.entry.main)];

  return singleSpaWebpackConfig
}`

Where within that chunk should the Patched code go?

**Comment by nmccrack37** [comment] 2022-01-04 19:04
``

> > Hi, a problem I ran into with Angular 13 was a webpack-dev-server config issue. Now Angular uses a webpack-dev-server version` >= 4.0.0` so [contentBase](https://github.com/single-spa/single-spa-angular/blob/4c36be60195d98073fdc82567721a8e724e023d4/libs/single-spa-angular/webpack/index.ts#L38) isn't a supported config property anymore. Using the `static` property instead of `contentBase` should solve the issue.
> 
> Same here, I patched the single-spa config for now by [following webpack doc](https://webpack.js.org/configuration/dev-server/#directory):
> 
> ```js
>   const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);
> 
>   const singleSpaWebpackConfigPatched = {
>     ...singleSpaWebpackConfig,
>     devServer: {
>       ...singleSpaWebpackConfig.devServer,
>       static: {
>           directory: singleSpaWebpackConfigPatched.devServer.contentBase,
>         },
>       }
>     },
>   };
>   delete singleSpaWebpackConfigPatched.devServer.contentBase;
> ```

Could you help me understand where this fits into my existing webpack.config?

```module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options)

  singleSpaWebpackConfig.entry.main = [...new Set(singleSpaWebpackConfig.entry.main)];

  return singleSpaWebpackConfig
}'''

**Comment by araza-mms** [comment] 2022-01-13 13:41
Any updates on this one?

**Comment by chucknelson** [comment] 2022-01-22 00:05
@joeldenning @arturovt - Just a reminder that this can be closed per #398 - thanks!

**Comment by arturovt** [comment] 2022-01-22 00:10
I'll keep it opened for some time if anyone will face any issue.

**Comment by ALP011216** [comment] 2022-01-24 14:14
After updating to version 6 I get the following error:
`An unhandled exception occurred: Package subpath './lib/webpack' is not defined by "exports" in .../node_modules/single-spa-angular/package.json`

I guess the issue is related to the custom webpack config:
`const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;`

Am I missing something here or should this work?

**Comment by arturovt** [comment] 2022-01-25 15:42
@ALP011216 made a PR with a fix: https://github.com/single-spa/single-spa-angular/pull/405

**Comment by jogelin** [comment] 2022-02-02 13:15
To unlock me until PR #405 is merged, I am using a hacky solution: [patch-package](https://github.com/ds300/patch-package).

- Install patch-package (read doc)
- update `node_modules/single-spa-angular/package.json` with:
```json
...
  "exports": {
    "./lib/webpack": {
      "default": "./lib/webpack/index.js"
    },
    ...
  }
```
- run `npx patch-package single-spa-angular --exclude 'nothing'`
- and it will generate a patch that you can apply each time by using `postinstall` (see doc)
```patch
diff --git a/node_modules/single-spa-angular/package.json b/node_modules/single-spa-angular/package.json
index 73ae5b0..8fb1f6c 100644
--- a/node_modules/single-spa-angular/package.json
+++ b/node_modules/single-spa-angular/package.json
@@ -36,6 +36,9 @@
   "fesm2015": "fesm2015/single-spa-angular.mjs",
   "typings": "single-spa-angular.d.ts",
   "exports": {
+    "./lib/webpack": {
+      "default": "./lib/webpack/index.js"
+    },
     "./package.json": {
       "default": "./package.json"
     },
```

**Comment by arturovt** [comment] 2022-02-14 03:32
I've published `single-spa-angular@6.0.1` with fixes, release notes are here https://github.com/single-spa/single-spa-angular/releases/tag/v6.0.1.

**Comment by tymfear** [comment] 2022-02-25 15:12
@arturovt so how does config should look like with that the latest version?

**Comment by arturovt** [comment] 2022-03-02 14:27
@tymfear sorry for the late response, hard times for Ukraine.. you shouldn't do any changes, just migrate the Angular and update `single-spa-angular` to `^6.0.0`.

**Comment by arturovt** [comment] 2022-03-15 22:50
I’ll close the issue. Feel free to open new issues if you encounter anything. It would be easier to track new issues since this one is over growing.

**Closed by arturovt** 2022-03-15 22:50 UTC

**Comment by tscislo** [comment] 2022-03-16 21:59
Thank you @arturovt! I just tested 6.0.2 with Angular 13.2.x and it works fine. Keep safe @arturovt!

**Comment by tymfear** [comment] 2022-03-17 12:07
So, when trying to upgrade I got now the problem that importmap override does not work on CI when we run e2e with Playwright (locally it works). And with v5 that is not an issue. Has anyone seen such issues?
