### ISSUE TITLE
npm package assets not loaded 

### ISSUE THREAD

**Issue by lyba-alphai** [single-spa/single-spa-angular#460] opened 2022-11-08 09:11 UTC
### Question
I am facing an issue in setting the url for assets that are used within packages. For example I am using a package "select-country" it has peer dependency of svg_flags. svg_flags exist in node_modules but my MFE is not able to get it's path. I do not know how to set these assets's path and where to set it.

**Comment by arturovt** [comment] 2022-11-10 20:43
I can't do more than closing this issue since it's not clear and doesn't have a reproducible example.

**Closed by arturovt** 2022-11-10 20:43 UTC
