### ISSUE TITLE
Code compialation problem in single-spa-angular/internals/types.d.ts

### ISSUE THREAD

**Issue by MedRAQAOUI** [single-spa/single-spa-angular#251] opened 2020-07-24 14:24 UTC
Hi,

On the code source file single-spa-angular/internals/types.d.ts for module single-spa-angular there is a compilation error.

import('@angular/core').NgZone syntax seems to be not correct

**Comment by joeldenning** [comment] 2020-07-24 17:04
Hi @MedRAQAOUI, could you provide more information about the error? Did you install single-spa-angular via `ng add single-spa-angular`? What version of single-spa-angular are you running? What version of Angular are you using?

**Comment by MedRAQAOUI** [comment] 2020-07-24 20:12
Hi Joel,

Thank you for your reply.
Yes single-spa-angular was installed via ng add single-spa-angular.

This is single-spa version :
"single-spa": "5.5.5",
"single-spa-angular": "^4.3.1",

And below  the stack :

Angular CLI: 9.0.7
Node: 12.16.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.2.4
@angular/flex-layout              9.0.0-beta.31
@angular/http                     7.2.16
@angular/material                 9.2.4
@angular/router                   9.1.12
@ngtools/webpack                  9.1.12
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0

Cordialement,
Mohamed RAQAOUI
Tél:0605687068


Le ven. 24 juil. 2020 à 19:04, Joel Denning <notifications@github.com> a
écrit :

**Comment by MedRAQAOUI** [comment] 2020-07-27 07:39
Hi,

"single-spa": "5.5.5", version was put manually , the original one it's >=4.0.0

Best reguards,
Mohamed RAQAOUI

**Comment by joeldenning** [comment] 2020-07-27 16:49
I tried this out locally with my local version of Angular CLI 9 and was unable to reproduce the issue. Could you provide a repository demonstrating the issue?

**Comment by MedRAQAOUI** [comment] 2020-07-27 17:11
![image](https://user-images.githubusercontent.com/31072563/88570714-d5b14080-d03c-11ea-809d-eeabc2a63066.png)

It's maby a typescript version issue ?

**Comment by MedRAQAOUI** [comment] 2020-07-27 17:13
This is after change syntaxe from import('@angular/core').NgZone  to NgZone :
![image](https://user-images.githubusercontent.com/31072563/88570932-2f196f80-d03d-11ea-968f-5a081d28811d.png)

**Comment by joeldenning** [comment] 2020-07-27 17:14
Please provide a github repo demonstrating the issue, as I mentioned in my last comment. Debugging without a github repo will be hard.

**Comment by MedRAQAOUI** [comment] 2020-07-27 19:11
![image](https://user-images.githubusercontent.com/31072563/88581445-77d92480-d04d-11ea-9697-707bd9ae6187.png)

I can't connect to repository on github.com from my company network :(

**Comment by MedRAQAOUI** [comment] 2020-07-27 19:48
[portal.zip](https://github.com/single-spa/single-spa-angular/files/4984115/portal.zip)

Here in attachement source code without node_modules directory.

npm install to show compilation  error 

npm run serve:single-spa:portail for start server dev

**Comment by MedRAQAOUI** [comment] 2020-07-28 14:21
Hi Joel,

I try to understand the issue , on repository git  single-spa/single-spa-angular there is the correct source code syntax in  src/internals/src/types.ts .

Is single-spa-angular/internals/types.d.ts a compilation of src/internals/src/types.ts  ?

**Comment by MedRAQAOUI** [comment] 2020-07-28 14:34
This code is introduced in PR feat(single-spa-angular): add possibility to have a zone-less application #182 on commit hash 81ebca381799cfc06ad95559de315cbf2ade2c22

**Comment by MedRAQAOUI** [comment] 2020-07-28 15:03
In fact dynamic import of NgZone in single-spa-angular/internals/types.d.ts  it does not seem to work.

**Comment by arturovt** [comment] 2020-08-09 19:31
This is not a _dynamic import_. It’s called _import type_ and was introduced in TS 2.9. This is a subtype of _type guard_ that ensures that we import only _the type itself_, and not the _NgZone_ class.

**Comment by arturovt** [comment] 2020-11-02 10:32
Closing this issue, since the import type was removed:

https://github.com/single-spa/single-spa-angular/blob/master/src/src/types.ts#L19

**Closed by arturovt** 2020-11-02 10:32 UTC
