### ISSUE TITLE
single-spa-angular multi layer of children

### ISSUE THREAD

**Issue by sylvester-x** [single-spa/single-spa-angular#400] opened 2021-12-06 06:42 UTC
Currently, I have 3 projects that need to link together.
Project 1 -> Main
Project 2 -> children of project 1
Project 3 -> children of project 2

I can link them together. But the problem is when navigating to the URL, the DOM initial load multiple times.

Project 1 routing:
![image](https://user-images.githubusercontent.com/45072247/144799704-185f448e-7078-4ad9-973c-4bef57e0c7e8.png)

Project 2 routing:
![image](https://user-images.githubusercontent.com/45072247/144799720-bd173a1d-26a8-4013-863a-221ee444fb31.png)

**Comment by joeldenning** [comment] 2021-12-27 21:41
> when navigating to the URL, the DOM initial load multiple times.

I don't understand this. What does "DOM initial load multiple times" mean? Is the page reloading?

**Comment by sylvester-x** [comment] 2021-12-28 02:23
Here is the example:
I placed the console on the constructor:
![image](https://user-images.githubusercontent.com/45072247/147520600-d99d99dd-a7b2-4b66-9b4f-c2981018c520.png)

Now I first time navigate to the page
![image](https://user-images.githubusercontent.com/45072247/147520731-1840af18-8d97-4fb8-b03d-4f7a8f06228f.png)

When I second navigate to the page
![image](https://user-images.githubusercontent.com/45072247/147520796-eba7b594-8ae8-417d-98db-c7597a8d2332.png)

**Comment by arturovt** [comment] 2022-04-10 15:54
Closing due to absence of the reproducible example, feel free to re-open when one is provided. I can't, unfortunately, tell you the reason why that might happen by looking at the image with `console.log` :(

**Closed by arturovt** 2022-04-10 15:54 UTC
