### ISSUE TITLE
Angular route navigation issue

### ISSUE THREAD

**Issue by saravanavel891** [single-spa/single-spa-angular#296] opened 2020-11-03 20:44 UTC
### Demonstration
We are trying to load our application using single spa. we are able to load and it is working as expected. The only scenario it is failing is hard reload is not taking us to the right page where we were before. in our app routing module we have empty route also.

**routes Array**: `routes =  [{
    path: '',
    redirectTo: '/test/default',
    pathMatch: 'full'
  },
{
path: 'default',
    component: DefaultComponent
},
{
path: 'route1',
    component: Route1Component,
}
]
RouterModule.forRoot(routes, { enableTracing: false, useHash: true })`

**default route**: /test/default

**previous route**: /test/route1

On reload we are storing the initial url in session and redirecting it using below code.

**Redirection code**: `this.router.navigateByUrl('/test/route1');`
### Expected Behavior
My application has to load previous route (/test/route1) and corresponding page.

### Actual Behavior
My application is loading default route (/test/default) and corresponding page. In console we are seeing "Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?"

**Comment by arturovt** [comment] 2020-11-04 12:08
@saravanavel891 could you provide a minimal reproducible example?

**Comment by arturovt** [comment] 2021-03-07 19:56
Hey @saravanavel891 

Closing this issue since the reproducible example is not provided and I'm not able to debug it.

Feel free to re-open when you have an example.

**Closed by arturovt** 2021-03-07 19:56 UTC
