### ISSUE TITLE
Lazy Load Module Not Working

### ISSUE THREAD

**Issue by aniketavhad13** [single-spa/single-spa-angular#137] opened 2020-02-26 15:21 UTC
I am using angular-7 with single-spa and want to load module using lazy load approach but unfortunately, I am getting 
```
core.js:15724 ERROR Error: Uncaught (in promise): SyntaxError: Unexpected token '<'
SyntaxError: Unexpected token '<'
    at resolvePromise (zone.js:836)
    at resolvePromise (zone.js:795)
    at zone.js:897
    at ZoneDelegate.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.invokeTask (zone.js:430)
    at Zone.runTask (zone.js:198)
    at drainMicroTaskQueue (zone.js:611)
    at ZoneTask.invokeTask [as invoke] (zone.js:517)
    at invokeTask (zone.js:1671)
```

 also chunk is not creating for lazy-load modules.

Can someone help me to get rid out of this.

**Comment by joeldenning** [comment] 2020-02-29 18:12
> SyntaxError: Unexpected token '<'

This usually means that the attempt to download the lazy loaded file is responding with an HTML file instead of a javascript file. Which means that the file is being downloaded from the wrong location.

Use `--deploy-url` as specified in https://single-spa.js.org/docs/ecosystem-angular#building. See example [here](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/package.json#L12).

Closing because I don't think there's a bug here with single-spa-angular (although perhaps the docs could be more clear that --deploy-url is needed for the serve command, too)

**Closed by joeldenning** 2020-02-29 18:12 UTC

**Comment by aniketavhad** [comment] 2020-03-04 05:34
I investigated the cause for this and came to conclusion that issue because of `"single-spa-angular": "^3.0.1`" cap in the version of single-spa.

When i removed cap from `package.json` and reinstall the dependency then it works for me.

**Comment by joeldenning** [comment] 2020-03-05 00:00
What cap are you referring to? The `^3.0.1` version of single-spa-angular should work fine - the `^` will install the latest version (3.1.0)

**Comment by aniketavhad** [comment] 2020-04-06 11:47
When trying to refresh lazy load module path in local environment then i am getting `Uncaught SyntaxError: Unexpected token '<'`.
I have added deploy-url too.

I am using `"single-spa-angular": "3.0.1"` version

Anything i am missing here to add?

**Comment by joeldenning** [comment] 2020-04-06 19:14
That error indicates that the URL you are attempting to download the single-spa application from responded with an HTML file instead of a JS file. This is often due to the reasons [described here](https://github.com/systemjs/systemjs/blob/error-codes/docs/errors.md#4)

**Comment by aniketavhad** [comment] 2020-04-07 04:44
Given link is not exist. can you please provide the valid link.

**Comment by aniketavhad** [comment] 2020-04-07 04:45
> That error indicates that the URL you are attempting to download the single-spa application from responded with an HTML file instead of a JS file. This is often due to the reasons [described here](https://github.com/systemjs/systemjs/blob/error-codes/docs/errors.md#4)

Given link is not exist. can you please provide the valid link.

**Comment by joeldenning** [comment] 2020-04-07 15:21
Ah the link was to a branch that was not yet merged into master yet - I merged it in yesterday and then deleted the branch, which is why the link no longer works.

Here's the new link - https://github.com/systemjs/systemjs/blob/master/docs/errors.md#4
Here's the PR I was referencing - https://github.com/systemjs/systemjs/pull/2151
