### ISSUE TITLE
Navigation Stops working after some time

### ISSUE THREAD

**Issue by pgarzina** [single-spa/single-spa-angular#446] opened 2022-07-01 14:10 UTC
### Environment

<pre><code>
Libs:
- @angular/core version: 12.2
- single-spa-angular version: 5.0.2
- single-spa: ^5.9.3,

</code></pre>

Hello,

I'm posting this in the questions section, in hopes of getting a quick answer if someone experienced the same issue.

Basically after we have our application opened for 1 hour plus without engagement and come back to it our main navigation stops working. Up until that point everything works fine.

The URL changes but the applications do not get mounted/unmounted.
We have two Angular applications opened simultaneously.

Thanks!

**Comment by arturovt** [comment] 2022-07-03 07:50
I can’t give any advice w/o a reproducible example, sorry. I’m closing it due to the lack of context. Feel free to reopen once you have a running app.

**Closed by arturovt** 2022-07-03 07:50 UTC
