### ISSUE TITLE
Mounting application 'app1' did not resolve or reject for 3000 milliseconds -- we're no longer going to warn you about it.

### ISSUE THREAD

**Issue by varunpandurangaiah** [single-spa/single-spa-angular#150] opened 2020-03-23 05:11 UTC
I am getting an error while mounting a boilerplate angular application, Any idea?

![image](https://user-images.githubusercontent.com/20150953/77283638-dafb2900-6cf2-11ea-961f-5550e9155429.png)

**Comment by joeldenning** [comment] 2020-03-24 15:12
The warning message means exactly what it says. The [`mount` lifecycle](https://single-spa.js.org/docs/building-applications#mount) is returning a promise that is never resolving / rejecting.

This is likely due to the code throwing an error during mount and is likely unrelated to single-spa.

**Comment by arturovt** [comment] 2020-04-06 19:59
@varunpandurangaiah could you provide a _minimal reproducible example_, please? Thus we could clone it locally, test it and help you to resolve an issue. W/o any reproduction the issue has to be closed and re-opened when it's provided.

**Comment by arturovt** [comment] 2020-04-14 09:08
@varunpandurangaiah any progress on this?

**Comment by joeldenning** [comment] 2020-04-14 23:16
Closing due to inactivity - feel free to reopen with a demonstration of the issue

**Closed by joeldenning** 2020-04-14 23:16 UTC
