### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by mohamedalijinnah** [single-spa/single-spa-angular#336] opened 2021-02-04 11:40 UTC
I'm facing issue after converting my angular 11 application to micro front end.

Followed this https://single-spa.js.org/docs/ecosystem-angular#angular-11 

After installing the single-spa-angular package when i do ng serve i get 

![image](https://user-images.githubusercontent.com/43814278/106887822-b5f58600-670b-11eb-9a5e-1b673f7470d5.png)

**Comment by filoxo** [comment] 2021-02-04 15:08
Duplicate of #328 which is still unresolved.

**Closed by filoxo** 2021-02-04 15:08 UTC
