### ISSUE TITLE
Getting a Uncaught Error: application 'angular' died in status SKIP_BECAUSE_BROKEN: "Failed to load app.component.html" when I try loading a simple angular component

### ISSUE THREAD

**Issue by hiskuDN** [single-spa/single-spa-angular#331] opened 2021-01-18 02:51 UTC
Here's a screenshot of the issue and I'm using Angular 6 with React
![image](https://user-images.githubusercontent.com/18376750/104867127-785ed200-5983-11eb-88c2-b917870c6b83.png)

**Comment by frehner** [comment] 2021-01-18 03:04
Have you gone to the url in the warning message and tried the recommendations there?

**Comment by arturovt** [comment] 2021-02-28 03:26
This seems like there is something wrong with your configuration. Could you provide a minimal reproducible example?

**Comment by joeldenning** [comment] 2021-03-01 18:38
This looks like you're loading html at templates at runtime - generally this is not done in Angular projects so it might be related to that.

**Comment by arturovt** [comment] 2021-11-11 17:34
I'll close it as "not an issue". Feel free to re-open with a reproducible example.

**Closed by arturovt** 2021-11-11 17:34 UTC
