### ISSUE TITLE
how to use Parcels in angular

### ISSUE THREAD

**Issue by jimyhdolores** [single-spa/single-spa-angular#237] opened 2020-07-07 04:59 UTC
### Question
Hello, I have used the CLI single-spa to create a Parcel project since, according to the documentation, this type of microfront is recommended to be able to share UI components in different frameworks, in the CLI it shows the options of which language to use, I chose React; Now I want to use this Parcel in an Angular project, but I can't find examples of how to do it, do you have any demo of Angular Parcel?

- @angular/core version: 9.1.0
- single-spa-angular version: 4.0.1

**Comment by filoxo** [comment] 2020-07-07 16:23
We have not yet had the time to document Angular Parcels, and the issue is tracked on the documentation repo https://github.com/single-spa/single-spa.js.org/issues/199

**Comment by R0muald** [comment] 2020-07-11 12:55
Would that be possible to get access to the angular app that you use to test out the Parcel component? I'm trying to get it to work with a simple spa app without success:
```html
<parcel *ngIf="!!spaSite" [config]="spaSite" [mountParcel]="mountParcel"> </parcel>
```
```ts
import { mountRootParcel} from "single-spa";
@Component({})
export class HomeComponent implements OnInit {
   mountParcel = mountRootParcel;
   spaSite;
   constructor(){}
   ngOnInit() {
    this.spaSite = window.System.import("spa-site");
    // also tried with
    // window.System.import("spa-site").then(mod => {
    //   this.spaSite = mod.default;
    // });
  }
}
```
**PS :** The "spa-site" is a spa application that works great when mounted with `registerApplication()`

**Comment by filoxo** [comment] 2020-07-12 00:13
@R0muald this [coexisting-angular-microfrontends repo](https://github.com/joeldenning/coexisting-angular-microfrontends) would likely be a good candidate to use.  You'll have to fork it but your changes might also be a good example to  contribute.

**Comment by R0muald** [comment] 2020-07-13 14:23
Thanks for the reply. 
To do that, I would need to transform the root-html app into an angular app. I will also need to remove the spa-layout since the Parcel will be mounted and unmounted from the angular app that will load/unload those routes. 
Is that a faire statement? Do you see a different way to explain the usage of Parcel?

Please let me know, so I can create the reference app and share it.

**Comment by joeldenning** [comment] 2020-07-13 17:05
Parcels were implemented in https://github.com/single-spa/single-spa-angular/pull/122 by @ricardofct.

@ricardofct could you comment here with example usage? We need to add this to the documentation.

**Comment by R0muald** [comment] 2020-07-13 18:41
Hi,
I created a `root-angular` app that follows the `root-html-file` but with an angular routing instead of the `single-spa-layout` routing.
It's a basic angular app with lazy loading. The setup I have regarding to the spa micro-app:
- `navbar` registered as an application (to insure that application and parcel can work together)
- `app1` loaded as parcel under `/app1` route
- `app2` loaded as parcel under `/app2` route

But I still have my issue: The `app1` and `app2` don't want to load in the parcel component and I'm not sure why. If someone wants to look at it that would be great!

My repo: https://github.com/R0muald/coexisting-angular-microfrontends

I can make a PR too if you want.

**Comment by filoxo** [comment] 2020-07-13 19:49
@R0muald I think you went the wrong direction with that. You do not have to implement the root-config with Angular in order to use Parcels, and [using a framework in the root-config is something we actively discourage](https://single-spa.js.org/docs/faq/#should-i-have-a-parentroot-app-and-children-apps). A Parcel is ["a chunk of functionality meant to be mounted manually by an application"](https://single-spa.js.org/docs/parcels-overview/) to interoperate between frameworks by leveraging single-spa's lifecycles. An example would be to create and share an Angular component within a React application.

**Comment by R0muald** [comment] 2020-07-13 20:20
Yes, I figured that I was stretching the usage of Parcels.
The issue I want to solve with Parcel:
- Have more control on when, where to load those micro-app without depending only on the route,
- Have a framework at the root to provide dynamic loading of micro-app and better communication between them

Is there anything that stop an application to be loaded as a parcel?

**Comment by filoxo** [comment] 2020-07-13 21:04
Those are good questions. I'd recommend joining our [Slack workspace](https://join.slack.com/t/single-spa/shared_invite/enQtODAwNTIyMzc4OTE1LWUxMTUwY2M1MTY0ZGMzOTUzMGNkMzI1NzRiYzYwOWM1MTEzZDM1NDAyNWM3ZmViOTAzZThkMDcwMWZmNTFmMWQ) to ask those questions because this issue is for tracking single-spa-angular Parcels documentation, and I'd rather not clutter it with tangential information.

**Comment by R0muald** [comment] 2020-07-13 22:01
Will update my fork to follow your recommendation

**Comment by awhitehouseWS** [comment] 2020-11-03 15:52
I see the docs don't exist yet, but is there an example repo out there anywhere?

**Comment by joeldenning** [comment] 2020-11-03 18:54
The parcel component and module are not currently compatible with Angular 9+. I tried it locally just now.

**Comment by joeldenning** [comment] 2020-11-03 18:55
![image](https://user-images.githubusercontent.com/5524384/98028478-654c5500-1dcb-11eb-9de7-4516040ffe2a.png)

**Comment by joeldenning** [comment] 2020-11-03 18:55
![image](https://user-images.githubusercontent.com/5524384/98028502-6e3d2680-1dcb-11eb-8396-08752863ed1b.png)

**Comment by joeldenning** [comment] 2020-11-03 18:55
https://stackoverflow.com/questions/60726180/angular-9-value-at-position-x-in-the-ngmodule-imports-is-not-a-reference

**Comment by awhitehouseWS** [comment] 2020-11-03 19:14
ah, ok. thank you for the quick response. may look into it if I have time

**Comment by joeldenning** [comment] 2020-11-06 16:39
Also, here's a rough idea of how to use the component once it's successfully imported and installed:

```js
import { mountRootParcel } from 'single-spa';

const parcelConfig = {
  async mount() {
    console.log('mounting!')
  },
  async unmount() {
    console.log('unmounting')
  }
}

// In angular template
<parcel [config]="parcelConfig" [mountParcel]="mountRootParcel" />
```

**Comment by joeldenning** [comment] 2020-11-09 22:09
The parcel component has been fixed in v4.7.0. The release notes have a link to an example, and @arturovt is putting together a PR for the documentation soon:

https://github.com/single-spa/single-spa-angular/releases/tag/v4.7.0

**Comment by joeldenning** [comment] 2020-11-10 17:42
Documentation is live at https://single-spa.js.org/docs/ecosystem-angular#parcels

**Closed by joeldenning** 2020-11-10 17:42 UTC

**Comment by danielgchap** [comment] 2021-06-04 19:57
> Documentation is live at https://single-spa.js.org/docs/ecosystem-angular#parcels

Seriously???? It exemplifies Parcels via react! Wow guys. "Lets make an angular component but not document". Really nice. smh

**Comment by joeldenning** [comment] 2021-06-07 18:26
@danielgchap your comment is not helpful. Single-spa is a community-owned project that operates via volunteer work and (minimal) donations. Since you're part of the community, perhaps you should take ownership of the documentation and submit an improvement, rather than criticizing the rest of the community you're part of?

**Comment by danielgchap** [comment] 2021-06-07 20:30
> @danielgchap your comment is not helpful. Single-spa is a community-owned project that operates via volunteer work and (minimal) donations. You received single-spa for free and do not have to use it if you do not want to. Since you're part of the community, perhaps you should take ownership of the documentation and submit an improvement, rather than criticizing the rest of the community you're part of?

As part of this community, maybe YOU should be more open to critique too. Perhaps YOU should take ownership too buddy. Your angular docs point to react examples. Your vanilla parcel project doesn't work. My apologies to the community. But balls up and take a criticism. Bad documentation LITERALLY takes away dev hours and your github / slack is riddled with people fighting angular based contingencies and the docs are lacking in that area. You

**Comment by awhitehouseWS** [comment] 2021-06-07 21:30
> > @danielgchap your comment is not helpful. Single-spa is a community-owned project that operates via volunteer work and (minimal) donations. You received single-spa for free and do not have to use it if you do not want to. Since you're part of the community, perhaps you should take ownership of the documentation and submit an improvement, rather than criticizing the rest of the community you're part of?
> 
> @joeldenning
> YOUR comment is not helpful. Everything I said on the docs was true. The harshest word I used was 'garbage' in the slack chat.
> 
> As part of this community, maybe YOU should be more open to critique too. Perhaps YOU should take ownership too, buddy. If you're going to stand as an advocate, then be one. You apparently have time to combat me on provable issues, direct that to your docs instead. Your angular docs point to react examples. Your vanilla parcel project doesn't work. My truest apologies to the community. But not you... balls up and take a criticism. Bad documentation LITERALLY takes away dev hours and your github / slack is riddled with people fighting angular based contingencies and the docs are lacking in that area. You ban me from the slack channel because I called you out on it. Banned for truthful criticism?.. none of which was impolite, cussing or rude. There's some advice for 'free'.

You're critiquing as if someone owes you something. Lack of docs wasting dev hours? People literally created this in their spare time so you can use it for free. It's an open source project. If you want better docs you write them.

**Comment by joeldenning** [comment] 2021-06-07 21:55
Thanks @awhitehouseWS. I'm going to lock this conversation to avoid it further devolving. The single-spa docs are by no means perfect, but the way to go about improving them is by offering your own time to submit pull requests, etc. Reporting issues with the documentation is also valid, but should be done in a respectful way that does not criticize the project, its maintainers, or its community.
