### ISSUE TITLE
Trying to integrate angular9 application

### ISSUE THREAD

**Issue by sanjanaadeshra** [single-spa/single-spa-angular#287] opened 2020-10-29 11:38 UTC
### Production Environment

<pre><code>
Libs:
- @angular/core version:~9.1.7
- single-spa-angular version: ^4.0.1

</code></pre>

I am trying to use an application built in angular 10. I am trying to include the build in main root-html application, but getting the following error, can you please help me out with it.

```
zone.js:192 Uncaught ReferenceError: global is not defined
    at Object.bBst (index.js:2)
    at __webpack_require__ (bootstrap:19)
```

**Comment by joeldenning** [comment] 2020-10-29 19:38
Angular 10 isn't fully supported by single-spa-angular. The issue title here indicates you're using Angular 10, but the code snippet you shared indicates 9.1.7. Which version of Angular is this for?

**Comment by sanjanaadeshra** [comment] 2020-10-30 06:48
With angular version 10 since compatibility was an issue, I've downgraded it down to 9.1.7, but still the same issue.

**Comment by arturovt** [comment] 2020-11-02 10:27
@sanjanaadeshra can you provide a minimal reproducible example?

**Comment by hervedevos** [comment] 2020-11-05 10:52
> Angular 10 isn't fully supported by single-spa-angular. The issue title here indicates you're using Angular 10, but the code snippet you shared indicates 9.1.7. Which version of Angular is this for?

@joeldenning  Can you detail what's missing ? I integrated an Angular 10 app and I didn't encounter any issues for now...

**Comment by arturovt** [comment] 2020-11-05 11:37
@hervedevos this repository contains 5 Angular applications for integration purposes and they all use the latest Angular version (10.2.0). Joel probably meant the issue that was encountered this summer related to `ng add` command.

**Comment by joeldenning** [comment] 2020-11-06 16:15
> Joel probably meant the issue that was encountered this summer related to ng add command. Angular 10 is supported.

Yes @arturovt is right here - angular 10 is supported. When I last commented I wasn't sure if there were still problems with the schematics, but there are not.

>  integrated an Angular 10 app and I didn't encounter any issues for now...

Sounds like the issue is resolved here - closing this issue now.

**Closed by joeldenning** 2020-11-06 16:15 UTC
