### ISSUE TITLE
Back Button Not working!!

### ISSUE THREAD

**Issue by ashuaggarwal94** [single-spa/single-spa-angular#94] opened 2019-07-09 09:50 UTC
Hi,

I have been facing an issue with the single spa framework and angular routing, in which when i move from one component after performing the functionality like search and then i move to another component. And then, press the browser back button and the UI is not getting rendered correctly or functionality doesn't work the way it should.
For reproducing the issue, the below repo has been created. and do find the video in the repo.

Repo: https://github.com/ashuaggarwal94/singleSPA1

**Comment by amaneer94** [comment] 2019-07-09 12:05
I am facing the same kinda problem.

**Comment by joeldenning** [comment] 2019-07-09 16:08
I'm taking a look at this now - hopefully I can find the issue.

**Comment by joeldenning** [comment] 2019-07-09 16:40
The behavior that I'm seeing is that the back button works but that when you attempt to search again that I get an error. Is the below gif what you're seeing?

![back-button-1](https://user-images.githubusercontent.com/5524384/60907056-db6f9480-a235-11e9-986c-4af011f755c6.gif)

**Comment by ashuaggarwal94** [comment] 2019-07-10 06:15
My bad!!! Changed the code, can you please pull the code changes and try now!! 
We are not getting the error now!! even in above case we should not have got the error. But we got. As of now instead of two way binding i have declared a template variable now.

Thanks,
Ashutosh

**Comment by joeldenning** [comment] 2019-07-18 16:38
With your new changes to the code, I am no longer seeing any errors and the back button is working perfectly. I tested in both Firefox and Chrome.

![back-button-bug](https://user-images.githubusercontent.com/5524384/61475474-18c7d680-a948-11e9-8b3e-569385adebee.gif)

Is this different than what you're seeing locally?

**Comment by joeldenning** [comment] 2019-08-01 16:06
<img width="864" alt="image" src="https://user-images.githubusercontent.com/5524384/62309086-fc499500-b443-11e9-8cfe-7653664f7c12.png">

Link to repo that demos the problem: https://github.com/korjikk/angular-single-spa-routing-issue

**Comment by ashuaggarwal94** [comment] 2019-08-02 14:03
Hi @joeldenning ,

I tried downgrading the router but it had started giving me error while i was building the project.
One more thing that i have observed is we are able to run the application if we are using enter (the way u are doing) but the submit button is not working!! 

<input (keyup.enter)="onClick()" />

We had found an alternative to the problem as of now by using ChangeDetectorRef and calling detectChanges method over the call.

Eg:

constructor(private ref: ChangeDetectorRef){}

onClick(value){
this.data.push(value);
this.ref.detectChanges();
}

Thanks,
Ashutosh

**Comment by rknash18** [comment] 2019-08-12 18:53
I am experiencing the similar issue when using the browser back button.

![back button issue](https://user-images.githubusercontent.com/36893778/62890091-541bb200-bd08-11e9-8c95-e6c60c0f39eb.gif)

**Comment by joeldenning** [comment] 2019-08-14 04:29
Since it's been hard for me to get around to this issue, I scheduled some time on my calendar Friday morning to look into this. Which will hopefully guarantee that some attention is given to this issue, since it appears to be severe and common.

**Comment by sand-head** [comment] 2019-08-14 19:28
we're running into a similar issue when using resolvers with our routing in two different Angular apps running on versions 7 & 8. 

starting on a route with a resolver attached, if we navigate off of that route using a `[routerLink]`, then click the native browser back button to head back to the original route, a `NavigationStart` event fires and we hit the resolver, but we then receive a `NavigationCancel` event, stating `Navigation ID (n) is not equal to the current navigation id (n + 1)`, with `n` being the current navigation ID. a second `NavigationStart` event then fires using that `n + 1` navigation ID ending with a similar result.

this only happens when a route has a resolver, and the back button works as intended for us in all other scenarios.

**Comment by sand-head** [comment] 2019-08-15 17:35
we've discovered that our issue was being caused by having more than one Angular router on page at a time when using a resolver on one of them and pressing either back or forward in the native browser controls. we're worked around this for now by removing the router on our navbar application, and things seem to be working well.

**Comment by joeldenning** [comment] 2019-08-16 17:14
@korjikk I just took a look at https://github.com/korjikk/angular-single-spa-routing-issue. There is no bug there. It does not demonstrate a problem with single-spa-angular. Instead it just is a duplicate of https://github.com/CanopyTax/single-spa-angular/issues/53, which is a harmless console warning.

I'm going to take a look into other github issues that reproduce this problem.

**Comment by joeldenning** [comment] 2019-08-16 17:15
@ashuaggarwal94 do you have a github issue that reproduces the problem? Our discussions above were me unsuccessfully trying to reproduce the problem, and the repo you provided did not demonstrate the problem.

**Comment by joeldenning** [comment] 2019-08-16 17:16
@rknash18 could you provide a github repo that replicates the issue. I am unable to fix this without having a way of reproducing the problem.

**Comment by joeldenning** [comment] 2019-08-16 17:21
@sand-head that's an interesting insight about Angular Router resolvers.

Could you create a github repo that demonstrates the problem that occurs when you have resolvers? Also, am I understanding you correctly that it was **only** happening when using a [resolver](https://angular.io/guide/router#fetch-data-before-navigating), not when there was no resolver?

**Comment by joeldenning** [comment] 2019-08-16 17:30
@amaneer94 I was able to reproduce the problem that you described in https://github.com/CanopyTax/single-spa-angular/issues/78#issuecomment-514569613 that is demonstrated by https://github.com/amaneer94/single-spa.

Your project does not have an Angular Router resolver like @sand-head indicated was part of his issue. I am taking a look at this right now to try to diagnose.

**Comment by joeldenning** [comment] 2019-08-16 17:47
I unfortunately have to take off right now, but learned a few things while looking at @amaneer94's issue. First thing is that I think that this might be related to #86. Which would explain why @ashuaggarwal94's code that does `this.ref.detectChanges();` is a work around for the problem.

Angular's change detection, which is related to NgZone and zone.js, is somehow getting confused such that it's not re-rendering angular things after things like click events.

I will try to take a look at this later today or tomorrow, but am not sure if I'll get to it. Might have to book some more time in my calendar to look at this.

**Comment by korjikk** [comment] 2019-08-16 18:57
@joeldenning , thank you for checking out the repo with the issue. Seems that i wasn't clear enough in stating the reproduction steps. Please check the GIF below, it clearly demonstrates the bug stated by me (routing breaks with 'single-spa').

![bug repro](https://user-images.githubusercontent.com/16175764/63191162-89116700-c070-11e9-88c6-a62f640a3ee1.gif)

**Comment by joeldenning** [comment] 2019-08-16 22:42
Ah okay, thanks for the clarification. I'll take a look at that repo while debugging this.

**Comment by joeldenning** [comment] 2019-11-07 07:47
Can those in this thread confirm if the workaround suggested in https://github.com/CanopyTax/single-spa-angular/issues/113#issuecomment-550442522 works for them?

If so let's try to incorporate it into single-spa-angular.

**Comment by vultix** [comment] 2019-11-22 07:43
@joeldenning That workaround does seem to fix the issue.

**Comment by joeldenning** [comment] 2019-11-24 19:50
> That workaround does not seem to fix the issue for me.

That's unfortunate. I do not plan on working on this issue in the near future and would gladly accept someone taking this up and finding a fix for it.

**Comment by erlloyd** [comment] 2020-03-20 05:23
I just wanted to add another example repo that shows the problem as well, which I'm using to dig into the problem as I have time: https://github.com/erlloyd/single-spa-poc

The repro steps once the repo is up and running are: 
1. Open http://localhost:9000
2. Click on the Ships navbar
3. click the Toggle button, notice how text appears and disappears
4. Click on Millineum Falcon. This hits another route in the angular microfrontend
5. Click the back button in the browser
6. Now try to click the Toggle button. Notice nothing happens
![single-spa-issue](https://user-images.githubusercontent.com/2145299/77138686-fd661b80-6a40-11ea-9f78-c7647f131e9a.gif)

**Comment by joeldenning** [comment] 2020-03-20 14:39
Hi @erlloyd - could you try out the new `urlRerouteOnly` option that was released yesterday in single-spa@5.2.0? More info at https://github.com/single-spa/single-spa/releases/tag/v5.2.0 and https://single-spa.js.org/docs/api/#start.

Another angular user indicated that this helped things for them - I have hopes that it might help this bug, too

**Comment by erlloyd** [comment] 2020-03-22 19:33
Unfortunately, @joeldenning One of the first things I tried was using the `urlRerouteOnly` flag with no change for this problem. In my case the problem exhibits from switching between two routes both handled by a micro-frontend written in angular 8, when using the back button. I'm still trying to investigate, but I believe it's definitely something that's messing up Zone.js

**Comment by arturovt** [comment] 2020-04-05 23:18
@erlloyd hey man. I cloned your repo and was able to reproduce your issue and reached the bottom of the Mariana Trench while debugging.

---

Yeah, it's related to zone.js. The problem is that zone.js patches `history.pushState` and tracks if it's called from the right context. `single-spa` overrides `history.replaceState`, if you log it to the console you'll see something like `ƒ (t){var n=vt.apply(this,arguments);return pt(gt(t)),n}`.

```ts
declare const Zone: any;

const originalReplaceState = history.replaceState;

history.replaceState = function() {
  console.log(Zone.current);
  return originalReplaceState.apply(this, arguments);
};
```

---

When I navigate by clicking on "Millineum Falcon" then it logs forked zone with `name: 'angular'`, if I click "back" button in the browser then it logs "<root>" zone.

The problem is here:

https://github.com/single-spa/single-spa-angular/blob/5cb144b2cce3cbf69c7030a1713b3006b370c6fa/src/browser-lib/single-spa-angular.ts#L61-L68

It's not enough to tell zone that something happened because what `NgZone.run` does is only notifies zone's `onInvoke` lifecycle hook which calls `ApplicationRef.tick()` accordingly.

The router also has to create a component inside the Angular's zone because it creates components manually via:
```ts
const factory = this.resolver.resolveComponentFactory(component);
this.activated = this.viewContainerRef.createComponent(factory, this.location.length, injector);
```

So here we will see `true` when we click on the "Millenium Falcon" and `false` when we click the browser's "back" button:
```ts
import { RouterOutlet } from '@angular/router';

const original = RouterOutlet.prototype.activateWith;

RouterOutlet.prototype.activateWith = function () {
  console.log(
    `RouterOutlet.activateWith() NgZone.isInAngularZone(): `,
    NgZone.isInAngularZone()
  );

  return original.apply(this, arguments);
};
```

---

So when we click the "back" button in our browser we'll see that our content gets renderer, but if we click the "Toggle" button then nothing will happen.

```ts
import { EventManager } from '@angular/platform-browser';

declare const Zone: any;

const original = EventManager.prototype.addEventListener;
EventManager.prototype.addEventListener = function (
  element: HTMLElement,
  eventName: string,
  handler: Function
) {
  return original.call(this, element, eventName, function () {
    if (eventName === 'click') {
      console.log(Zone.current);
    }

    return handler.apply(this, arguments);
  });
};
```

The same goes here. The event listener is actually added, but its callback is invoked in the root zone, thus Angular doesn't run change detection.

---

**AT THE END OF THE DAY** I managed to fix it by adding this code to the `mount` function inside the `single-spa-angular`:
```js
const router = module.injector.get(opts.Router);
router.locationSubscription.unsubscribe();
router.locationSubscription = router.location.subscribe((change) => {
  let rawUrlTree = router.parseUrl(change['url']);

  const source = change['type'] === 'popstate' ? 'popstate' : 'hashchange';
  const state = change.state && change.state.navigationId ? change.state : null;
  const scheduleNavigation = () =>
    setTimeout(() => {
      router.scheduleNavigation(rawUrlTree, source, state, {
        replaceUrl: true,
      });
    }, 0);

  if (opts.NgZone.isInAngularZone()) {
    scheduleNavigation();
  } else {
    opts.bootstrappedNgZone.run(scheduleNavigation);
  }
});
```

@joeldenning cc. What do you think?

**Comment by erlloyd** [comment] 2020-04-06 14:40
@arturovt That analysis is awesome! It seems to confirm what I was seeing but couldn't get to the bottom of. Obviously yanking code from @angular/router isn't the best from a maintainability standpoint (for example, I'm curious if this will continue to work with angular 9) but I think it makes sense why it fixes the issue!

**Comment by arturovt** [comment] 2020-04-06 14:46
@erlloyd 

> Obviously yanking code from @angular/router isn't the best from a maintainability standpoint

You're 100% right. I am not a fan of this solution either. I will try to look for other approaches but it definitely will require something "to patch" and "to wrap into zone".

**Comment by arturovt** [comment] 2020-04-06 16:02
@erlloyd 

> for example, I'm curious if this will continue to work with angular 9

It will. This piece of router code has never changed. I made a PR yesterday (#153) to add support for Angular 9 that resolves multiple issues. Awaiting captain! :D

**Comment by joeldenning** [comment] 2020-04-06 18:16
> @joeldenning cc. What do you think?

Thanks for the very in-depth analysis. Nice work on it. Let's try out your solution and see if it helps everyone out.

One question on it, that we could maybe talk about in a PR, is whether `replaceUrl` should always be true, or should only be true if the URL has changed? But let's get your PR up and discuss it there.

**Comment by arturovt** [comment] 2020-04-07 13:34
@erlloyd 

I'm working on adding E2E tests that will be a quality gate and provide a way of "sanity check" to ensure that issues are resolved. I was able to reproduce the current behaviour there:

https://github.com/single-spa/single-spa-angular/pull/156/files#diff-564a9067420e8879beb180b8e6b77b77

Regarding this issue, so we have 2 options to go with:

1) that option I proposed with patching router location and scheduling navigation inside Angular's zone
2) another option is to provide custom `PlatformLocation`, since there is a huge chain of providers that deal with browser's location, something like:

_Router_ -> _uses_ -> _Location_ -> _uses_ -> _PathLocationStrategy_ -> _uses_ -> _PlatformLocation_.

Yeah, a big level of abstraction and dependency inversion. So the second option technically could look like this:

```ts
import singleSpaAngular, { getSingleSpaExtraProviders } from 'single-spa-angular';

const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    singleSpaPropsSubject.next(singleSpaProps);
    return platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule);
  },
  template: '<super-app />',
  Router,
  NgZone,
});
```

Which would do under the hood:

```ts
import {
  PlatformLocation,
  ɵBrowserPlatformLocation,
  LocationChangeEvent,
  DOCUMENT,
} from '@angular/common';

@Injectable()
export class SingleSpaPlatformLocation extends ɵBrowserPlatformLocation {
  constructor(@Inject(DOCUMENT) document: Document) {
    super(document);
  }

  onPopState(fn: (event: LocationChangeEvent) => void): void {
    const ngZone = inject(NgZone);

    window.addEventListener(
      'popstate',
      event => ngZone.run(() => fn((event as unknown) as LocationChangeEvent)),
      false
    );
  }
}

export function getSingleSpaExtraProviders(): StaticProvider[] {
  return [
    {
      provide: PlatformLocation,
      useClass: SingleSpaPlatformLocation,
      deps: [[new Inject(DOCUMENT)]],
    },
  ];
}
```

The first option will not require library-consumers to do anything, just upgrade the version.

**Comment by joeldenning** [comment] 2020-04-07 15:40
Hmm I tend to agree that implementing a custom PlatformLocation seems more maintainable and less of a workaround. I think that it would be reasonable for us to expect existing users to add `getSingleSpaExtraProviders` to their code to get this bug fix. For new projects, we can add the single spa providers to the main.single-spa.ts template, so that people don't have to think about it. I vote we go with Option 2

**Comment by erlloyd** [comment] 2020-04-08 01:40
I've been following this thread, and I'll also say I prefer option 2. I agree that requiring a manual update for library consumers is preferable in my opinion to patching existing APIs...

**Comment by joeldenning** [comment] 2020-04-18 19:46
This is now fixed in single-spa-angular@4, which only works in Angular 9. We will publish a new version of single-spa-angular@3 hopefully soon with the fix for Angular 2-8.

https://github.com/single-spa/single-spa-angular/releases/tag/v4.0.0

**Comment by joeldenning** [comment] 2020-04-19 03:05
The router patch approach has been implemented in #173 and released in https://github.com/single-spa/single-spa-angular/releases/tag/v3.3.1. This is for Angular versions 2-8. This bug is finally fixed (we think)! Big thanks to @arturovt for finding and fixing this.

**Closed by joeldenning** 2020-04-19 03:05 UTC
Labels: priority: critical, ready to release, type: bug/fix

**Comment by zpc0921** [comment] 2021-07-19 13:12
hi when i use navigate, with {replaceUrl: true}, then it not work，how to resolve, please?

**Comment by joeldenning** [comment] 2021-07-19 20:13
Please create a new issue, as that seems unrelated to this issue.
