### ISSUE TITLE
Injector has already been destroyed

### ISSUE THREAD

**Issue by JohnnyHonorato** [single-spa/single-spa-angular#389] opened 2021-09-27 13:54 UTC
### Demonstration

https://user-images.githubusercontent.com/20287365/134922471-2132d05b-1b9b-4a4d-80f6-2cc05325bc33.mp4

### Expected Behavior

I have two SingleSPA Angular applications, and they are loaded with LazyLoading:

 {
        path: 'tracker',
        children: [
            {
                path: '**',
                loadChildren: () => import('./shared/spa-host/spa-host.module').then(m => m.SpaHostModule),
                data: {app: 'tracker'}
            }
        ]
    }

When I change routes from a SingleSPA to another, the system stops working. Another point that I observe is that the error occurs because of the Injector class that I use when I make the AppModule.

constructor(private injector: Injector) {
        setAppInjector(this.injector);
    }

On the first loading the SingleSPA works fine, the system brakes only when the route change occurs.

Dependencies I work with:

"@angular/animations": "~12.2.6",
"@angular/cdk": "^12.2.5",
"@angular/flex-layout": "^12.0.0-beta.34",
"@angular/common": "~12.2.6",
"@angular/compiler": "~12.2.6",
"@angular/core": "~12.2.6",
"@angular/forms": "~12.2.6",
"@angular/platform-browser": "~12.2.6",
"@angular/platform-browser-dynamic": "~12.2.6",
"@angular/router": "~12.2.6",
"single-spa": "^5.9.3",
"single-spa-angular": "^5.0.2",
"@angular-builders/custom-webpack": "^12.1.2",
"@angular-devkit/build-angular": "~12.2.6",

Can anybody help?

### Actual Behavior

![image](https://user-images.githubusercontent.com/20287365/134922579-4435ff87-60f9-4e1b-99ec-afef35f7f3dc.png)

**Comment by joeldenning** [comment] 2021-09-28 16:26
I don't spend much time maintaining single-spa-angular, but welcome and review any pull requests fixing issues. There aren't many others who actively help in maintaining the project right now, but I'll leave this issue open for others to comment on.

**Comment by arturovt** [comment] 2021-11-11 17:33
Can you provide a minimal reproducible example? Unfortunately, I can't make any assumptions from your video.

**Comment by arturovt** [comment] 2022-03-15 22:51
I’ll close the issue since I can’t, unfortunately, make any conclusion what might cause it without reproducible example, feel free to reopen when you have one.

**Closed by arturovt** 2022-03-15 22:51 UTC
