### ISSUE TITLE
Zone error coming up after the navigation(Cannot read property 'run' of undefined)

### ISSUE THREAD

**Issue by ashuaggarwal94** [single-spa/single-spa-angular#201] opened 2020-05-27 06:23 UTC
After navigating from the portal application we are getting in the console.

Log trace:
core.js:6228 ERROR TypeError: Cannot read property 'run' of undefined
    at eval (single-spa-angular.js:21)
    at eval (single-spa.min.js:2)
    at Array.forEach (<anonymous>)
    at et (single-spa.min.js:2)
    at m (single-spa.min.js:2)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41654)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Object.onInvoke (core.js:28134)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Object.onInvokeTask (zone-evergreen.js:273)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Object.onInvokeTask (core.js:28122)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ____________________Elapsed_165_ms__At__Wed_May_27_2020_11_34_17_GMT_0530__India_Standard_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.js:110)
    at ZoneDelegate.scheduleTask (zone-evergreen.js:378)
    at Object.onScheduleTask (zone-evergreen.js:272)
    at ZoneDelegate.scheduleTask (zone-evergreen.js:378)
    at Object.onScheduleTask (long-stack-trace-zone.js:126)

Please let me know in case any further detail is required.

**Comment by joeldenning** [comment] 2020-05-27 16:55
What version of Angular and single-spa-angular are you using? Could you please share the contents of main.single-spa.ts? Specifically I am interested in whether `NgZone` and single-spa extra providers are being passed into singleSpaAngular(). The stacktrace indicates that one of the following lines is throwing an error, due to ngZone not being set up properly. The simplest explanation for this would be if you're not passing in the single-spa extra providers, as described in https://single-spa.js.org/docs/ecosystem-angular#basic-usage

https://github.com/single-spa/single-spa-angular/blob/389a16cb186ed5fd975199ff2e4670084c47a84f/src/src/single-spa-angular.ts#L77

https://github.com/single-spa/single-spa-angular/blob/389a16cb186ed5fd975199ff2e4670084c47a84f/src/src/extra-providers.ts#L63

https://github.com/single-spa/single-spa-angular/blob/389a16cb186ed5fd975199ff2e4670084c47a84f/src/src/single-spa-angular.ts#L138-L139

**Comment by joeldenning** [comment] 2020-05-27 16:56
Another question, if you're using Angular@<9 is if you're sharing dependencies between multiple microfrontends.

**Comment by ashuaggarwal94** [comment] 2020-05-28 05:07
Hi Joel,

Thanks for the quick reply!!

main.singlespa.js
import { enableProdMode, NgZone } from '@angular/core';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { Router } from '@angular/router';
import { ɵAnimationEngine as AnimationEngine } from '@angular/animations/browser';

import { singleSpaAngular, getSingleSpaExtraProviders } from 'single-spa-angular';


import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    return platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule);
  },
  template: '<app-cec/>',
  Router,
  NgZone: NgZone,
  AnimationEngine,
});

export const bootstrap = lifecycles.bootstrap;
export const mount = lifecycles.mount;
export const unmount = lifecycles.unmount;


We are using angular version 9+, single spa version 5.5.1, and single-spa-angular 4.1.0.

package json dependency:
"dependencies": {
    "@angular/animations": "~9.1.9",
    "@angular/common": "~9.1.9",
    "@angular/compiler": "~9.1.9",
    "@angular/core": "~9.1.9",
    "@angular/forms": "~9.1.9",
    "@angular/platform-browser": "~9.1.9",
    "@angular/platform-browser-dynamic": "~9.1.9",
    "@angular/router": "~9.1.9",
    "@intershop/living-styleguide": "file:@intershop/living-styleguide",
    "@ng-bootstrap/ng-bootstrap": "^6.0.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular2-uuid": "^1.1.1",
    "animate": "^1.0.0",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "jquery": "3.4.1",
    "ngx-toastr": "^10.0.4",
    "ngx-translate-multi-http-loader": "^3.0.0",
    "node-sass": "4.12.0",
    "rxjs": "~6.5.5",
    "rxjs-compat": "^6.5.2",
    "single-spa": "^5.5.1",
    "single-spa-angular": "4.1.0",
    "tslib": "^1.10.0",
    "uuid": "^3.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^9",
    "@angular-devkit/build-angular": "~0.901.6",
    "@angular/cli": "~9.1.6",
    "@angular/compiler-cli": "~9.1.9",
    "@angular/language-service": "~9.1.9",
    "@types/jest": "^25.1.2",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jest": "^25.1.0",
    "jest-preset-angular": "^8.0.0",
    "popper.js": "^1.16.0",
    "replace-in-file": "^4.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.8.3"
  }

Do let me know in case any other detail is required.

Thanks,
Ashutosh

**Comment by joeldenning** [comment] 2020-05-28 15:49
I'm wondering if this is occurring when a popstate event is fired to the Angular platform before the single-spa-angular application is mounted. If so, the following might be a good fix?

```typescript
    const onPopStateListener = (event: LocationChangeEvent) => {
      // The `LocationChangeEvent` doesn't have the `singleSpa` property, since it's added
      // by `single-spa` starting from `5.4` version. We need this check because we want
      // to skip "unnatural" PopStateEvents, the one caused by `single-spa`.
      const popStateEventWasDispatchedBySingleSpa = !!((event as unknown) as { singleSpa: boolean })
        .singleSpa;

      if (this.skipNextPopState && popStateEventWasDispatchedBySingleSpa) {
        this.skipNextPopState = false;
      } else if (this.ngZone) {
        // Wrap any event listener into zone that is specific to some application.
        // The main issue is `back/forward` buttons of browsers, because they invoke
        // `history.back|forward` which dispatch `popstate` event. Since `single-spa`
        // overrides `history.replaceState` Angular's zone cannot intercept this event.
        // Only the root zone is able to intercept all events.
        // See https://github.com/single-spa/single-spa-angular/issues/94 for more details
        this.ngZone.run(() => fn(event));
      }
    };
```

@arturovt can you comment on this, and whether it's possible for a popstate event to fire before the application has been mounted?

**Comment by arturovt** [comment] 2020-05-28 15:58
Can we see a reproducible example?

**Comment by ashuaggarwal94** [comment] 2020-05-29 05:48
@joeldenning I also tried to debug the issue and feel the same. But will try and get u the repo by today.

Thanks,
Ashutosh

**Comment by werts** [comment] 2020-06-01 01:54
@ashuaggarwal94 the same,this.ngZone.run is not a function,because this.ngzone is undefined

**Comment by ashuaggarwal94** [comment] 2020-06-01 05:33
@arturovt I tried creating a repo but the problem is it's not reproducible in the small repo that I was trying to build. I will try and give the repo to you asap.
Thanks,
Ashutosh

**Comment by ashuaggarwal94** [comment] 2020-06-01 10:38
@werts  hey my issue is resolved. I was using singlespa.navigatetoUrl function in the child application which was causing the issue. As of now, I have changed back to using the router lib.

Thanks,
Ashutosh

**Comment by ashuaggarwal94** [comment] 2020-06-01 11:42
HI @joeldenning , @arturovt ,

sample repo: https://github.com/ashuaggarwal94/issue201

Thanks,
Ashutosh

**Comment by arturovt** [comment] 2020-06-01 11:46
Thanks, I will have a look asap.

**Comment by ashuaggarwal94** [comment] 2020-06-01 13:27
@arturovt   thanks, and do let me know in case any other detail is required.

Thanks,
Ashutosh

**Comment by werts** [comment] 2020-06-01 13:29
@ashuaggarwal94 Ok,i will try that! Thanks

**Comment by arturovt** [comment] 2020-06-05 13:39
@joeldenning as I mentioned in chat that this issue was fixed after upgrading version.

**Comment by joeldenning** [comment] 2020-06-05 16:15
Yes can you confirm @werts @ashuaggarwal94 what version of single-spa-angular you are using?

**Comment by ashuaggarwal94** [comment] 2020-06-08 05:40
@joeldenning , for both the portal and the child I am using 5.5.1.

**Comment by joeldenning** [comment] 2020-06-08 16:16
`5.5.1` is a `single-spa` version, but my question is what is the the `single-spa-angular` version. Specifically I'm interested to know whether you're using single-spa-angular@3 or single-spa-angular@4. And then which exact version within those that you are using.

What version of single-spa-angular you are using?

**Comment by joeldenning** [comment] 2020-06-08 16:20
From your example repo, it looks like you're using single-spa-angular@4.1.0:

https://github.com/ashuaggarwal94/issue201/blob/77b28aaf31aca933b4912e26121517628373c56b/ish-cec/package.json#L26

https://github.com/ashuaggarwal94/issue201/blob/77b28aaf31aca933b4912e26121517628373c56b/ish-cec/package-lock.json#L10712

Try upgrading to single-spa-angular@4.2.0, which changed this behavior:

https://github.com/single-spa/single-spa-angular/releases/tag/v4.2.0

I am closing this issue since @arturovt confirmed that upgrading to single-spa-angular@4.2.0 fixed this. Feel free to comment further or reopen if that is not the case.

**Closed by joeldenning** 2020-06-08 16:20 UTC

**Comment by ashuaggarwal94** [comment] 2020-06-08 18:19
Thanks @joeldenning @arturovt for the help the issue got resolved after updating the package!!!
