### ISSUE TITLE
ng schematics not registering correct extra-webpack path w/ multi-project repository structure

### ISSUE THREAD

**Issue by Lykathia** [single-spa/single-spa-angular#127] opened 2020-02-10 14:11 UTC
ng new --createApplication false workspace
    cd workspace
    ng g application demo
    ng add single-spa-angular

Followed by running the application, results in:

    An unhandled exception occurred: Cannot find module '/path/to/workspace/root/./extra-webpack.config.js'

I believe it is just missing the project path in the schematic:
https://github.com/single-spa/single-spa-angular/blob/f72e44099c97d5da2b1dd4589cf8f05dc7daba0d/src/schematics/ng-add/index.ts#L114

```typescript
  clientProject.architect.build.options.customWebpackConfig = {
    path: "./extra-webpack.config.js"
  }
  // @ts-ignore
  clientProject.architect.build.options.main = 'src/main.single-spa.ts'
```

=>
```typescript
  clientProject.architect.build.options.customWebpackConfig = {
    path: `${clientProject.root}/extra-webpack.config.js`
  }
  // @ts-ignore
  clientProject.architect.build.options.main = `${clientProject.root}/src/main.single-spa.ts`
```

Would put this in a PR, but, don't have a real project to regression test against, and make sure everything still works. Still evaluating various microfrontend strategies :)

**Comment by Lykathia** [comment] 2020-02-10 14:17
Looks like the path issue is present in a few of the `angular.json` file modifications.

**Comment by joeldenning** [comment] 2020-02-12 03:14
Was this with Angular 8 or Angular 9? Did you run ng serve in the root directory, or inside of `projects/demo`?

I tried this with both Angular 8 and 9 locally  and was unable to reproduce that problem.

**Comment by Lykathia** [comment] 2020-02-12 03:19
Angular 9, all from the root directory. I messed up and had `ng add single-spa-angular` should be `ng add single-spa-angular --project demo`. I had reproduced twice, was a very clean project.

**Comment by joeldenning** [comment] 2020-02-12 03:25
I was able to reproduce the error this time. Here were the steps I took:

```sh
ng new angular-test --routing --prefix angular-test
cd angular-test
ng g application demo
ng add single-spa-angular --project demo
ng serve --project demo
```

I had never tried serving an Angular sub project before, which likely is why this was never addressed. Your proposed fix of switching to `${clientProject.root}/extra-webpack.config.js` sounds great to me. Would you be willing to send in a PR to fix?

**Comment by Lykathia** [comment] 2020-02-12 04:46
Sure thing -- I wasn't super confident what ripple effects there could be when I opened this issue, but I've been playing around with everything a lot more since then. Looks pretty isolated.

I'll try to get something up tomorrow, or, at least by week end.

**Comment by Lykathia** [comment] 2020-02-21 17:19
note: life and work both got pretty crazy for various reasons. Haven't forgotten about this :)

**Comment by joeldenning** [comment] 2020-02-23 18:58
👍 no problem - looking forward to your PR

**Comment by joeldenning** [comment] 2020-04-18 19:55
This is now released in single-spa-angular@4

**Closed by joeldenning** 2020-04-18 19:55 UTC
Labels: priority: high, ready to release, type: bug/fix
