### ISSUE TITLE
Shared service between apps in single spa

### ISSUE THREAD

**Issue by LuuLinhSon** [single-spa/single-spa-angular#444] opened 2022-06-29 07:29 UTC
I have a service is a class. Name is AuthService. But when I import it to a other application. I install it in contructor. private auth: AuthService. But i face error inject() must be called from an injection context. How to fix it. Thanks all

**Comment by arturovt** [comment] 2022-07-03 16:12
I can’t guess what is happening until the reproducible example is provided. Closing due to the lack of information.

**Closed by arturovt** 2022-07-03 16:12 UTC
