### ISSUE TITLE
single-spa-angular externals not working for Angular 8

### ISSUE THREAD

**Issue by xiaomengHuang** [single-spa/single-spa-angular#144] opened 2020-03-17 03:12 UTC
as the title, i got some problems when use single spa angular for Angular 8.

after adding single-spa-angular to the project, when i update the externals in the extra-webpack.config.js, the externals is not working. here is the code.

```
const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;
const webpackMerge = require("webpack-merge");

module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options);
  const singleSpaConfig = {
    output: {
      library: 'app2',
      libraryTarget: 'umd',
      filename: '[name].js'
    },
    externals: {
      "rxjs": "rxjs",
      "@angular/core": "ng.core",
    }
  };
  const mergedConfig = webpackMerge.smart(singleSpaWebpackConfig, singleSpaConfig);
  return mergedConfig;
}
```
it's not working in Angular 8 but working in Angular 7, same code.

in Angular 8 i got an error in Container Project.

Unable to resolve specifier 'ng.core'

**Comment by joeldenning** [comment] 2020-03-17 23:09
Are you using SystemJS as the module loader? Or what is providing the externals to the bundle?

If you are using SystemJS, check your import map for `ng.core`. You can do this by checking the browser dev tools Inspector tab and looking for `systemjs-importmap`.

You can also check it by running the following in the browser console:

```js
// if this throws an error, it means it's missing from the import map
System.resolve('ng.core')

// Try this as well if the resolve() works correctly
System.import('ng.core').then(m => console.log('angular core', m))

**Comment by xiaomengHuang** [comment] 2020-03-19 06:43
@joeldenning Sorry, maybe i didn't say it clearly.

first, in my case i have 6 micro front-end need to be display in the same page, so what i'm trying to do is reduce the bundle size, remove the same framework scripts from each micro front-end. That's the reason why i put the `@angular/core` in the externals.

second, let me list my steps here:

* add the script global name in the externals. like `@angular/core`, after i manual include the script in container project's Angular.json, it will declare a global variable  called global.ng.core and map it to `@angular/core`

* in the container project, manual include those scripts in angular.json, like bellow.
```
"scripts": [
              "node_modules/systemjs/dist/system.min.js",
              "node_modules/systemjs/dist/extras/amd.min.js",
              "node_modules/systemjs/dist/extras/named-exports.min.js",
              "node_modules/systemjs/dist/extras/named-register.min.js",
              "node_modules/import-map-overrides/dist/import-map-overrides.js",
              "node_modules/rxjs/bundles/rxjs.umd.js",
              "node_modules/@angular/core/bundles/core.umd.js",
              "node_modules/@angular/common/bundles/common.umd.js",
              "node_modules/@angular/common/bundles/common-http.umd.js",
              "node_modules/@angular/compiler/bundles/compiler.umd.js",
              "node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
              "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"
            ]
```

this solution works fine in Angular 7 but not working in Angular 8.

here is the code in github.

https://github.com/xiaomengHuang/NG-MicroFrontEnd

app1, app2 and container project are Angular 8.
app4 is Angular 7.

what i did is use Angular cli new a project and add single-spa-angular. 


and one more thing is this solution not work for me. i tried before.

```
{
    externals: {
      "rxjs": "rxjs",
      "@angular/core": "@angular/core",
    }
}
```

**Comment by joeldenning** [comment] 2020-03-22 03:53
Hi @xiaomengHuang - I cloned your repo and tried it locally and it appeared to me that the externals were working. Could you clarify what error you are experiencing? Is there a stacktrace you could share?

**Comment by arturovt** [comment] 2020-04-10 19:56
I cloned this repo and tried to install dependencies, unfortunately I even weren't able to do that :mask: 

I'm not knowledgeable in SystemJS and how it works. But what I can say is that there is a constraint of using that approach.

When you do this:
```js
externals: {
  '@angular/core': 'ng.core'
},
```

During the module concatenation process to create a main chunk Webpack maps module name to the module code wrapped into factory. So except of mapping `@angular/core` like this:
```js
{
  '@angular/core': (module, exports) => {
    // here is the code from node_modules/@angular/fesm2015/core.js
  }
}
```

It maps like this:
```js
{
  '@angular/core': (module, exports) => {
    module.exports = ng.core;
  }
}
```

When you want to share dependencies via `ng.core` that means that all micro-frontends will use the single `ng.core.NgZone` class and every last loaded micro-frontend will override `isInAngularZone` that will return invalid value for other consumers. It's frustrating, yes. But this is how it works.

**Comment by arturovt** [comment] 2020-04-10 21:52
I'm closing this issue because:
* reproduction is not quite reproducible because I wasn't even able to install packages because of npm errors... :slightly_smiling_face: 
* the implementation is not possible due to `NgZone` constraint

Feel free to open another issue if some problem really presents! :)

**Closed by arturovt** 2020-04-10 21:52 UTC
Labels: wontfix
