### ISSUE TITLE
single-spa routing doesn't work after deployment to apache directory

### ISSUE THREAD

**Issue by jyoti0291** [single-spa/single-spa-angular#300] opened 2020-11-10 16:12 UTC
The root application always loads default app.

My deployment location is http://example.co.jp/emp

On load I am able to load the following default application

http://example.co.jp/emp#login

But when I try to navigate to my second app using  http://example.co.jp/emp/user/list, I get redirected to default app with following url:

http://example.co.jp/emp/user/list#login

The APP_BASE_HREF for my second app is '/' and the router path is 'user'.

Everything seems to be working when my deployment location is http://example.co.jp , but because of some permission issues we can't make the final deployment to this location.

I am not able to figure out the root cause of this behavior. Tried apache rewrite rule as well but nothing seems to be working for this.

Any help would be really appreciated.

**Comment by joeldenning** [comment] 2020-11-10 17:40
Hi @jyoti0291, I've transferred this issue to the single-spa-angular repo since it seems you're using Angular (APP_BASE_HREF).

> But when I try to navigate to my second app using http://example.co.jp/emp/user/list, I get redirected to default app with following url:
>
> http://example.co.jp/emp/user/list#login

Could you clarify what you expect to happen? Did you expect the URL not to have the `#login` part in it? Or what is wrong.

Additionally, if you could provide a demonstration of the issue, that would help a lot.

**Comment by jyoti0291** [comment] 2020-11-10 18:03
Thanks so much for quick response @joeldenning 

`Could you clarify what you expect to happen? Did you expect the URL not to have the #login part in it? Or what is wrong.`

I want my second app to load when I hit http://example.co.jp/emp/user/list as per my following router configuration

<single-spa-router>
      <nav class="topnav">
        <application name="navbar"></application>
      </nav>
      <div class="main-content">
        <div id="home-app"></div>
        <route default>
          <application name="emp"></application>
        </route>
        <route path="user">
          <application name="user"></application>
        </route>
      </div>
      <application name="footer"></application>
    </single-spa-router>

But instead it loads the default app which is <application name="emp"></application> 

Default **emp** app is working fine on initial load

<img width="1393" alt="Screen Shot 2020-11-10 at 23 21 02" src="https://user-images.githubusercontent.com/22149791/98712398-4130db00-23ac-11eb-9bb7-43696da247a5.png">

Expected **user** screen on hitting http://example.co.jp/emp/user/list

<img width="1396" alt="Screen Shot 2020-11-10 at 23 22 05" src="https://user-images.githubusercontent.com/22149791/98712510-6887a800-23ac-11eb-90d3-1f716f966cb8.png">

But instead getting following screen which is again my default app:

<img width="1394" alt="Screen Shot 2020-11-10 at 23 22 24" src="https://user-images.githubusercontent.com/22149791/98712792-c1574080-23ac-11eb-9235-f8535d34480a.png">

The application is working as per the expectation when my deployment location is http://example.co.jp instead of http://example.co.jp/emp

**Comment by joeldenning** [comment] 2020-11-11 01:23
Seems like you have two different paths: `/emp/user` and `/user`. The single-spa-layout config you showed only matches the `/user` route, not the `/emp` route. This could be caused by your link's href not starting with `/`. The link should be an absolute url -  not page-relative url.

**Comment by jyoti0291** [comment] 2020-11-11 08:37
> The link should be an absolute url - not page-relative url.

Could you please elaborate this? Are you talking about the path in single-spa-layout config?

Actually the application and the routing is working properly when I am deploying the application to the root of the apache server e.g. http://example.co.jp because base href is `/` for the application

And if I am deploying it inside a directory e.g. http://example.co.jp/emp, `emp` is a directory is apache server. The routing doesn't work and I guess the root cause is `base href "/"` but I am not able to resolve the issue by adding /emp/ in the paths of the route.

**Comment by joeldenning** [comment] 2020-11-11 17:21
> But when I try to navigate to my second app using http://example.co.jp/emp/user/list, I get redirected to default app with following url:

`/emp/user` is the wrong URL for the user application, based on your single-spa-layout route definitions. This is what I mean.

```html
<!-- wrong -->
<a [routerLink]="['user']">
  This is a relative link instead of absolute
</a>

<!-- correct -->
<a [routerLink]="['/user']">
  This is an absolute link
</a>
```

**Closed** 2022-03-16 00:15 UTC
