### ISSUE TITLE
Can't add react application in angular as parcel app

### ISSUE THREAD

**Issue by bullypb23** [single-spa/single-spa-angular#335] opened 2021-02-04 09:19 UTC
Hi,

I am trying to use a single spa framework in my project and I want to build react and angular parcel apps and use them in angular and react applications as parcels. I have a problem with adding react application to angular as parcel app and I keep getting this error.

![image](https://user-images.githubusercontent.com/55666396/106870715-b5d89480-66d1-11eb-8475-40b47961112d.png)

My angular application code where I want to use this parcel app.

![image](https://user-images.githubusercontent.com/55666396/106870882-ea4c5080-66d1-11eb-9a34-ed154dea95aa.png)

![image](https://user-images.githubusercontent.com/55666396/106870944-ff28e400-66d1-11eb-9aad-f7b26acc7037.png)

The other way around I succeeded but I keep getting this error for this case. Would appreciate help regarding my issue.

**Comment by filoxo** [comment] 2021-02-04 14:30
The problem is that you're using a relative import (`import { bootstrap, mount, unmount } from '../../../react-test/src/thingsolver-react-test'`). This is not how Parcels work. 

First, you cannot import a React component directly into your Angular application. By using a relative import, that React component is being pulled into your Angular application and put through Angular's Webpack build pipeline which does not support React. Instead, that Parcel needs to be built and served separately in order to be able to resolve it at runtime using SystemJS and [cross microfronted imports](https://single-spa.js.org/docs/recommended-setup/#cross-microfrontend-imports).

Second, your Parcel is already exporting the lifecycles so you to not need to import the individual lifecycles to create this object. Just do `import * as thingsolverReactTestParcelConfig from 'thingsolver-react-test'`.

**Comment by bullypb23** [comment] 2021-02-04 15:17
Thank you for your response. Now I get this error. Do I need to change webpack config for my route angular application?

![image](https://user-images.githubusercontent.com/55666396/106913659-82632d80-6704-11eb-8a40-f186b2d7ce4b.png)

**Comment by filoxo** [comment] 2021-02-04 15:28
You need to do two things: 

1. Ensure that that package is in the `externals` array of your webpack config so that webpack knows that it should not try to bundle that module into your application, and
2. Obtain types for it somehow so that TypeScript will allow it to compile; the options for this are described in these issues
    - https://github.com/single-spa/single-spa/issues/609#issuecomment-665132965
    - https://github.com/single-spa/single-spa.js.org/issues/361#issuecomment-737259914

You can either enumerate each package to be marked as external or [use a regex](https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L89) like our other base webpack configs do. I'm not super familiar with how Angular allows devs to modify their webpack configs, but our docs have an example of adding to the externals here: https://single-spa.js.org/docs/ecosystem-angular/#inter-app-communication-via-rxjs

**Comment by bullypb23** [comment] 2021-02-04 15:50
Thank you @filoxo very much, you solved my problem. If I would have any questions in the future regarding this same problem I would ask them here.

**Comment by filoxo** [comment] 2021-02-04 16:00
Glad you were able to get it working! I'm going to ahead and close this issue. Feel free to reopen if you encounter more bugs/issues, and you can always ask questions in the [Slack channel](https://join.slack.com/t/single-spa/shared_invite/zt-l2iljnpv-pW_o92mMpMR8RWfIOI6pTQ) too.

**Closed by filoxo** 2021-02-04 16:00 UTC
