### ISSUE TITLE
Build error after update to Angular 14 with 'single-spa-angular' v7.0.0

### ISSUE THREAD

**Issue by akhila2708** [single-spa/single-spa-angular#442] opened 2022-06-23 12:56 UTC
As per below GitHub Link recommendation
https://github.com/single-spa/single-spa-angular/issues/440. 
We upgraded single-spa-angular package to v7.0.0.  But the build is failing because of below issue.

Issue:
Error: node_modules/single-spa-angular/src/public_api.d.ts:2:34 - error TS2307: Cannot find module './single-spa-angular' or its corresponding type declarations.
2 export { singleSpaAngular } from './single-spa-angular';

Cause:
‘single-spa-angular.ts’ file is missing in the ‘src’ folder of the 'single-spa-angular' library installed via npm. However, when we checked in the GitHub link of the library 
"https://github.com/single-spa/single-spa-angular/tree/master/libs/single-spa-angular/src"
this particular file is present. Not sure why this file is missing when we install with ‘npm’. 

Please check on this issue and let us know the resolution.

**Comment by arturovt** [comment] 2022-06-23 15:57
I can't give any more advice without a reproduction. I'm closing the issue, feel free to re-open when the reproduction is provided.

**Closed by arturovt** 2022-06-23 15:57 UTC

**Comment by sachin7062** [comment] 2022-06-24 05:39
I also have observed the same issue. when i did **npm i single-spa-angular** it downloaded single-spa-angular having src file only below 4 items 
node_modules\single-spa-angular\src\extra-providers.d.ts, 
node_modules\single-spa-angular\src\prod-mode.d.ts,
node_modules\single-spa-angular\src\public_api.d.ts,
node_modules\single-spa-angular\src\types.d.ts

but if we see the code of public.api.d.ts file it have reference for singleSpaAngular as below
export { enableProdMode } from './prod-mode';
export { singleSpaAngular } from './single-spa-angular';
export { getSingleSpaExtraProviders } from './extra-providers';

but there is no file downloaded with name singleSpaAngular in node_modules\single-spa-angular\src location.

When i check the GIT location https://github.com/single-spa/single-spa-angular/tree/master/libs/single-spa-angular/src i found the the file single-spa-angular.ts which didn't come with npm install.

I did the work around. Just copy pasted this file manually and Issue Fixed !!! Application started.

But definitely  there is some issue in npm install.

**Comment by sachin7062** [comment] 2022-06-27 04:55
Hi @arturovt,

I think, I have added the reproduction steps in the previous comment. This is very simple.

1. In a clean/new Angular project, we need the hit the command **npm i single-spa-angular**.  It downloads single-spa-angular and make an entry into package.json **"single-spa-angular": "^7.0.0",**
2. It downloads the package but at location **node_modules\single-spa-angular\src**, we don't see the file single-spa-angular.ts downloaded. Ideally it should be there, otherwise application can't build.

I hope this will help, Let me know if you need any more info.

**Comment by sachin7062** [comment] 2022-06-27 05:03
Hi @arturovt,

It looks like, I don't have access to re-open this issue as it is closed by collaborator.

Please help to re-open this, as this is one of the major blocker for us while upgrading the application to Angular 14 with single-spa-angular 7.0.0.

**Comment by akhila2708** [comment] 2022-06-27 05:09
Hi @arturovt ,

Please find below steps to reproduce the issue:

Issue:
Error: node_modules/single-spa-angular/src/public_api.d.ts:2:34 - error TS2307: Cannot find module './single-spa-angular' or its corresponding type declarations.
2 export { singleSpaAngular } from './single-spa-angular';

Steps to reproduce:
Step1: Created a brand new Angular 14 application.
Step2: Installed single-spa into application of version '5.9.3' using command 'npm i single-spa@5.9.3'
Step2 : Installed single-spa-angular with version 7.0.0 using command 'npm i single-spa-angular@7.0.0'
Step3: Tried to compile the application using 'ng serve'
Step4: compilation failed with below error:

Issue:
Error: node_modules/single-spa-angular/src/public_api.d.ts:2:34 - error TS2307: Cannot find module './single-spa-angular' or its corresponding type declarations.
2 export { singleSpaAngular } from './single-spa-angular';

Expected Behavior
Application should be build/compiled successfully

Actual Behavior
Build error in application

Cause:
‘single-spa-angular.ts’ file is missing in the ‘src’ folder of the 'single-spa-angular' library installed via npm. However, when we checked in the GitHub link of the library
"https://github.com/single-spa/single-spa-angular/tree/master/libs/single-spa-angular/src"
this particular file is present. Not sure why this file is missing when we install with ‘npm’.

Please check on this issue and let us know the resolution.

**Comment by arturovt** [comment] 2022-07-04 18:11
I have published 7.0.1. This has been a regression in ng-packagr itself. I closed the issue because I wasn't able to replicate this behavior in the current workspace. Sorry for the inconvenience.

**Comment by sachin7062** [comment] 2022-07-05 06:26
Thanks for the fix @arturovt.
