### ISSUE TITLE
Lazy load module not working in angular 8

### ISSUE THREAD

**Issue by ramakrishnajkm** [single-spa/single-spa-angular#284] opened 2020-10-14 15:29 UTC
Not able loadChildren module using single spa in angular 8 . I’m getting below screenshots errors. Can you help please me out

### Environment

<pre><code>
Libs:
![643074AF-F3A1-4BF8-B80E-9A2AB92DE5A6](https://user-images.githubusercontent.com/72873258/96010976-66174a00-0e10-11eb-9c9c-a013caefaefd.jpeg)
![C6A69992-06FD-4892-9449-D4018BF65085](https://user-images.githubusercontent.com/72873258/96010994-6a436780-0e10-11eb-840d-52b9a0963b8a.jpeg)

- @angular/core version: 8.2.14
- single-spa-angular version: 3.6.0

Others:

</code></pre>

**Comment by filoxo** [comment] 2020-10-23 16:24
Possible duplicate of #218. Perhaps the solutions provided in https://github.com/single-spa/single-spa-angular/issues/218#issuecomment-647050919 or https://github.com/single-spa/single-spa-angular/issues/218#issuecomment-647058204 can be helpful in solving this.

**Comment by arturovt** [comment] 2020-11-02 10:28
@ramakrishnajkm could you provide a minimal reproducible example?

**Comment by arturovt** [comment] 2020-11-14 19:42
@ramakrishnajkm unfortunately, I can’t say anything from these screenshots. Angular 8 uses another syntax for lazy loading tho, you have to replace it:
```ts
// before
loadChildren: './abc/abc.module#AbcModule'
// after
loadChildren: () => import('./abc/abc.module').then(m => m.AbcModule),
```
It's more imperative and doesn't have any side effects, compared to `loadChildren` which accepts string. At least we use this syntax in our integration applications.

Feel free to re-open with more information!

**Closed by arturovt** 2020-11-14 19:42 UTC
