### ISSUE TITLE
Sharing Angular (v9-10) via Webpack Externals throws "could not retrieve extra providers from the platform injector" error 

### ISSUE THREAD

**Issue by OriolInvernonLlaneza** [single-spa/single-spa-angular#288] opened 2020-10-30 11:36 UTC
I've been trying to update our apps to Angular 9 or 10 as we are still on 8. We have Angular depencies externalized and shared from the root config to all MFEs and this has provoked a problem when trying to update. The process I've followed so far can be read on[ this thread on the slack channel](https://single-spa.slack.com/archives/CGETM8T5X/p1603443658129000).

The complete error thrown, although `getSingleSpaExtraProviders` gets called on every app, reads as follows:
`Uncaught Error: single-spa-angular: could not retrieve extra providers from the platform injector. Did you call platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule()?`

### Demonstration
I prepared a simple repo where the error is thrown: https://github.com/OriolInvernonLlaneza/single-spa-angular-shared 
The project is made with `create-single-spa` so to run it just execute the `serve:single-spa` scripts.

### Expected Behavior
Angular microfrontends load, bootstrap, mount and unmount correctly as with version 8 of the framework when Angular dependencies are shared via Webpack Externals.

### Actual Behavior
Mounting process throws `single-spa-angular: could not retrieve extra providers from the platform injector. Did you call platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule()?` error although it's being called in the `main.single-spa.ts` of all microfrontends involved. The apps get mounted and look functional but crash when trying to unmount and trying to navigate back to them. 
When there's only one app being loaded at the same time and it's the first one to do so, it doesn't throw the error but the other will do it anyways. Navigating back to initital one won't show anything as the mounting process won't be executed.

**Comment by joeldenning** [comment] 2020-10-30 16:43
I don't have plans to look into this myself in the near future, but welcome a PR to fix it.

**Comment by arturovt** [comment] 2020-11-02 10:22
Hey @OriolInvernonLlaneza 

Thank you for provided reproduction. I've managed to clone it and to run locally. Basically what we have:
* you're sharing dependencies. You're also sharing Angular dependencies, that means that you've got 1 PLATFORM_INJECTOR per ALL apps
* you're not sharing `single-spa-angular`

What happens then? When writing `getSingleSpaExtraProviders()` it provides `PlatformLocation` in the platform injector. It was provided once when the `nav` application was loaded. Then we navigate to `/main/app` and the `app` application tries to retrieve `PlatformLocation`  via `SingleSpaPlatformLocation`. But the `PlatformLocation` was provided using the `SingleSpaPlatformLocation` class from nav's bundle.

Basically... references differ, since these are different bundles (single-spa-angular is bundled individually per each application).

What I've done:
* I have added `/^single-spa-angular$/` to each `extra-webpack.config.js` (app, nav, login)
* I have added single-spa-angular URL to systemjs-importmap:
```json
"single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.8.0/lib/umd/single-spa.min.js",
"single-spa-angular/internals": "https://cdn.jsdelivr.net/npm/single-spa-angular@4.5.0/bundles/single-spa-angular-internals.umd.js",
"single-spa-angular": "https://cdn.jsdelivr.net/npm/single-spa-angular@4.5.0/bundles/single-spa-angular.umd.js",
```

That's what I got:

![image](https://user-images.githubusercontent.com/7337691/97857243-1dafc580-1d06-11eb-8223-1465b13443c0.png)

**Comment by OriolInvernonLlaneza** [comment] 2020-11-02 13:42
Oh.., I don't even know how it didn't even cross my mind to share single-spa-angular, I'm a little bit mad with myself right now :)
Thank you very much for the quick answer, I'll try tomorrow with our real apps and close the issue if I don't encounter any other problem.

**Comment by joeldenning** [comment] 2020-11-02 17:52
Thanks @arturovt! Closing this.

**Closed by joeldenning** 2020-11-02 17:52 UTC

**Comment by OriolInvernonLlaneza** [comment] 2021-06-07 12:02
Sorry for reusing this issue but I have found this problem again and sharing `single-spa-angular` is not working.
I was trying to activate Ivy and use the esm-bundles you provide to prepare for upgrading to Angular 12. However, I get the following error:
```
Uncaught TypeError: Class constructor BrowserPlatformLocation cannot be invoked without 'new'
    at new SingleSpaPlatformLocation (extra-providers.ts:13)
```
I looked up the [angular-microfrontends repo](https://github.com/angular-microfrontends) and saw that it is not sharing `single-spa-angular`. I changed it on my apps but I got the `"could not retrieve extra providers"` error again.

Angular on the package.json:
```
  "dependencies": {
    "@angular/common": "~11.1.1",
    "@angular/compiler": "~11.1.1",
    "@angular/core": "~11.1.1",
    "@angular/forms": "~11.1.1",
    "@angular/platform-browser": "~11.1.1",
    "@angular/platform-browser-dynamic": "~11.1.1",
    "@angular/router": "~11.1.1",
    "angular-i18next": "~10.2.0",
    "i18next": "^20.3.1",
    "rxjs": "^6.6.0",
    "single-spa": "~5.8.0",
    "single-spa-angular": "~4.9.0",
    "zone.js": "~0.11.4"
  },
```
The webpack config:
```
module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options);

  singleSpaWebpackConfig.externals.push(
    /^@monitor\/*/,
    /^single-spa$/,
    /^single-spa-angular$/,
    /^single-spa-angular\/internals$/,
    /^rxjs$/,
    /^rxjs\/operators$/,
    /^@angular\/core$/,
    /^@angular\/common$/,
    /^@angular\/router$/,
    /^@angular\/platform-browser$/,
    /^zone\.js$/,
    /^i18next$/,
  );
 return singleSpaWebpackConfig
}
```
Shared dependencies on importmap:
```
        "@angular/core": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__core@11.1.1/system/es2015/ivy/angular-core.js",
        "@angular/common": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__common@11.1.1/system/es2015/ivy/angular-common.js",
        "@angular/router": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__router@11.1.1/system/es2015/ivy/angular-router.js",
        "@angular/platform-browser": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__platform-browser@11.1.1/system/es2015/ivy/angular-platform-browser.js",
       
        "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.9.3/lib/umd/single-spa.dev.js",
        "single-spa-angular": "https://cdn.jsdelivr.net/npm/single-spa-angular@4.9.2/bundles/single-spa-angular.umd.js",
        "single-spa-angular/internals": "https://cdn.jsdelivr.net/npm/single-spa-angular@4.9.2/bundles/single-spa-angular-internals.umd.js",
    
        "rxjs": "https://cdn.jsdelivr.net/npm/rxjs@6.6.3/bundles/rxjs.umd.js",
        "rxjs/operators": "https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@6.6.3/system/es5/rxjs-operators.min.js",

        "i18next": "https://unpkg.com/i18next/dist/umd/i18next.js",
        "i18next-browser-languagedetector": "https://cdnjs.cloudflare.com/ajax/libs/i18next-browser-languagedetector/4.2.0/i18nextBrowserLanguageDetector.js"
```
and main.single-spa.ts:
```
const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    singleSpaPropsSubject.next(singleSpaProps);

    i18next.loadNamespaces('login').then(() => {
      i18next.addResourceBundle('en', 'login', resources.en, true, true);
      i18next.addResourceBundle('es', 'login', resources.es, true, true);
    });

    return platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule);
  },
  domElementGetter,
  template: '<login-root />',
  Router,
  NgZone,
  NavigationStart
});
```
Hoping for some information. Thanks again!

**Comment by joeldenning** [comment] 2021-06-07 18:31
This github issue is about sharing Angular, not about sharing single-spa-angular. Please create a new issue or comment on a more relevant issue.

My understanding is that sharing single-spa-angular never really worked, which is why it isn't being done in angular-microfrontends. I think there's an open issue in single-spa-angular that describes why it's not shareable, but don't know which one it is. @daniloesk talked to me about it a while back - can you comment on it further?

**Comment by OriolInvernonLlaneza** [comment] 2021-06-08 08:26
At least sharing it "worked" with ViewEngine and Angular 9 to 11 because I set it up like that after this answer https://github.com/single-spa/single-spa-angular/issues/288#issuecomment-720380317 above and has been working fine so far. I'll search for the issue you mention or make a new one then, thanks!
