### ISSUE TITLE
Can I serve single-spa Sub Application both as normal and in root app using single dist build?

### ISSUE THREAD

**Issue by shashravi9** [single-spa/single-spa-angular#211] opened 2020-06-05 06:30 UTC
### Question
Hello,
I am using angular 8 for my Sub application and it works well with root app using single-spa. But, my question is can a single dist build serve as both a normal application(runs independently in browser) as well as a Single-spa sub app?

Please suggest me how it can be done. I need to run in both ways (host Sub-app independently as well as accessible from Root-app as well)

**Comment by filoxo** [comment] 2020-06-05 15:01
I believe this is a duplicate of #92 and the answer remains the same. So I'll close this for now but feel free to ask additional questions.

**Closed by filoxo** 2020-06-05 15:01 UTC
